# Server settings  
server:  
    port: 8080  
    address: localhost  
  
# SPRING PROFILES  
spring:         
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true
    datasource:
        name: gendb  
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/policesys?useConfigs=maxPerformance&characterEncoding=utf8
        username: root  
        password:
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false

# MyBatis
mybatis:
    typeAliasesPackage: cn.qsky.policesys.core.dao.model
    mapperLocations: classpath:/com/tasly/erp/repository/mapper/*.xml
    configLocation: classpath:/mybatis-config.xml

# LOGGING
logging:
    level:
       com.ibatis:DEBUG
      