package cn.qsky.policesys.core.dao.model;

import java.util.Date;

public class GroupRecordModel {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.PK
   *
   * @mbg.generated
   */
  private Long pk;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.created_time
   *
   * @mbg.generated
   */
  private Date createdTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.modified_time
   *
   * @mbg.generated
   */
  private Date modifiedTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.group_name
   *
   * @mbg.generated
   */
  private String groupName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.record_date
   *
   * @mbg.generated
   */
  private Date recordDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.score
   *
   * @mbg.generated
   */
  private Byte score;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.petition_location
   *
   * @mbg.generated
   */
  private String petitionLocation;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.petition_region
   *
   * @mbg.generated
   */
  private String petitionRegion;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.petition_dynamic
   *
   * @mbg.generated
   */
  private String petitionDynamic;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.confirm
   *
   * @mbg.generated
   */
  private Boolean confirm;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.incite_method
   *
   * @mbg.generated
   */
  private String inciteMethod;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.info_sources
   *
   * @mbg.generated
   */
  private String infoSources;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.action_group
   *
   * @mbg.generated
   */
  private String actionGroup;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.group_size
   *
   * @mbg.generated
   */
  private Short groupSize;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.consequence
   *
   * @mbg.generated
   */
  private Boolean consequence;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.conse_score
   *
   * @mbg.generated
   */
  private Byte conseScore;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.petition_situation
   *
   * @mbg.generated
   */
  private String petitionSituation;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.ext1
   *
   * @mbg.generated
   */
  private String ext1;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.ext2
   *
   * @mbg.generated
   */
  private String ext2;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.ext3
   *
   * @mbg.generated
   */
  private String ext3;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * group_record.delete_flag
   *
   * @mbg.generated
   */
  private Boolean deleteFlag;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.PK
   *
   * @return the value of group_record.PK
   * @mbg.generated
   */
  public Long getPk() {
    return pk;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.PK
   *
   * @param pk the value for group_record.PK
   * @mbg.generated
   */
  public void setPk(Long pk) {
    this.pk = pk;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.created_time
   *
   * @return the value of group_record.created_time
   * @mbg.generated
   */
  public Date getCreatedTime() {
    return createdTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.created_time
   *
   * @param createdTime the value for group_record.created_time
   * @mbg.generated
   */
  public void setCreatedTime(Date createdTime) {
    this.createdTime = createdTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.modified_time
   *
   * @return the value of group_record.modified_time
   * @mbg.generated
   */
  public Date getModifiedTime() {
    return modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.modified_time
   *
   * @param modifiedTime the value for group_record.modified_time
   * @mbg.generated
   */
  public void setModifiedTime(Date modifiedTime) {
    this.modifiedTime = modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.group_name
   *
   * @return the value of group_record.group_name
   * @mbg.generated
   */
  public String getGroupName() {
    return groupName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.group_name
   *
   * @param groupName the value for group_record.group_name
   * @mbg.generated
   */
  public void setGroupName(String groupName) {
    this.groupName = groupName == null ? null : groupName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.record_date
   *
   * @return the value of group_record.record_date
   * @mbg.generated
   */
  public Date getRecordDate() {
    return recordDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.record_date
   *
   * @param recordDate the value for group_record.record_date
   * @mbg.generated
   */
  public void setRecordDate(Date recordDate) {
    this.recordDate = recordDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.score
   *
   * @return the value of group_record.score
   * @mbg.generated
   */
  public Byte getScore() {
    return score;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.score
   *
   * @param score the value for group_record.score
   * @mbg.generated
   */
  public void setScore(Byte score) {
    this.score = score;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.petition_location
   *
   * @return the value of group_record.petition_location
   * @mbg.generated
   */
  public String getPetitionLocation() {
    return petitionLocation;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.petition_location
   *
   * @param petitionLocation the value for group_record.petition_location
   * @mbg.generated
   */
  public void setPetitionLocation(String petitionLocation) {
    this.petitionLocation = petitionLocation == null ? null : petitionLocation.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.petition_region
   *
   * @return the value of group_record.petition_region
   * @mbg.generated
   */
  public String getPetitionRegion() {
    return petitionRegion;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.petition_region
   *
   * @param petitionRegion the value for group_record.petition_region
   * @mbg.generated
   */
  public void setPetitionRegion(String petitionRegion) {
    this.petitionRegion = petitionRegion == null ? null : petitionRegion.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.petition_dynamic
   *
   * @return the value of group_record.petition_dynamic
   * @mbg.generated
   */
  public String getPetitionDynamic() {
    return petitionDynamic;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.petition_dynamic
   *
   * @param petitionDynamic the value for group_record.petition_dynamic
   * @mbg.generated
   */
  public void setPetitionDynamic(String petitionDynamic) {
    this.petitionDynamic = petitionDynamic == null ? null : petitionDynamic.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.confirm
   *
   * @return the value of group_record.confirm
   * @mbg.generated
   */
  public Boolean getConfirm() {
    return confirm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.confirm
   *
   * @param confirm the value for group_record.confirm
   * @mbg.generated
   */
  public void setConfirm(Boolean confirm) {
    this.confirm = confirm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.incite_method
   *
   * @return the value of group_record.incite_method
   * @mbg.generated
   */
  public String getInciteMethod() {
    return inciteMethod;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.incite_method
   *
   * @param inciteMethod the value for group_record.incite_method
   * @mbg.generated
   */
  public void setInciteMethod(String inciteMethod) {
    this.inciteMethod = inciteMethod == null ? null : inciteMethod.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.info_sources
   *
   * @return the value of group_record.info_sources
   * @mbg.generated
   */
  public String getInfoSources() {
    return infoSources;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.info_sources
   *
   * @param infoSources the value for group_record.info_sources
   * @mbg.generated
   */
  public void setInfoSources(String infoSources) {
    this.infoSources = infoSources == null ? null : infoSources.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.action_group
   *
   * @return the value of group_record.action_group
   * @mbg.generated
   */
  public String getActionGroup() {
    return actionGroup;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.action_group
   *
   * @param actionGroup the value for group_record.action_group
   * @mbg.generated
   */
  public void setActionGroup(String actionGroup) {
    this.actionGroup = actionGroup == null ? null : actionGroup.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.group_size
   *
   * @return the value of group_record.group_size
   * @mbg.generated
   */
  public Short getGroupSize() {
    return groupSize;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.group_size
   *
   * @param groupSize the value for group_record.group_size
   * @mbg.generated
   */
  public void setGroupSize(Short groupSize) {
    this.groupSize = groupSize;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.consequence
   *
   * @return the value of group_record.consequence
   * @mbg.generated
   */
  public Boolean getConsequence() {
    return consequence;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.consequence
   *
   * @param consequence the value for group_record.consequence
   * @mbg.generated
   */
  public void setConsequence(Boolean consequence) {
    this.consequence = consequence;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.conse_score
   *
   * @return the value of group_record.conse_score
   * @mbg.generated
   */
  public Byte getConseScore() {
    return conseScore;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.conse_score
   *
   * @param conseScore the value for group_record.conse_score
   * @mbg.generated
   */
  public void setConseScore(Byte conseScore) {
    this.conseScore = conseScore;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.petition_situation
   *
   * @return the value of group_record.petition_situation
   * @mbg.generated
   */
  public String getPetitionSituation() {
    return petitionSituation;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.petition_situation
   *
   * @param petitionSituation the value for group_record.petition_situation
   * @mbg.generated
   */
  public void setPetitionSituation(String petitionSituation) {
    this.petitionSituation = petitionSituation == null ? null : petitionSituation.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.ext1
   *
   * @return the value of group_record.ext1
   * @mbg.generated
   */
  public String getExt1() {
    return ext1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.ext1
   *
   * @param ext1 the value for group_record.ext1
   * @mbg.generated
   */
  public void setExt1(String ext1) {
    this.ext1 = ext1 == null ? null : ext1.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.ext2
   *
   * @return the value of group_record.ext2
   * @mbg.generated
   */
  public String getExt2() {
    return ext2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.ext2
   *
   * @param ext2 the value for group_record.ext2
   * @mbg.generated
   */
  public void setExt2(String ext2) {
    this.ext2 = ext2 == null ? null : ext2.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.ext3
   *
   * @return the value of group_record.ext3
   * @mbg.generated
   */
  public String getExt3() {
    return ext3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.ext3
   *
   * @param ext3 the value for group_record.ext3
   * @mbg.generated
   */
  public void setExt3(String ext3) {
    this.ext3 = ext3 == null ? null : ext3.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column group_record.delete_flag
   *
   * @return the value of group_record.delete_flag
   * @mbg.generated
   */
  public Boolean getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column group_record.delete_flag
   *
   * @param deleteFlag the value for group_record.delete_flag
   * @mbg.generated
   */
  public void setDeleteFlag(Boolean deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}