package cn.qsky.policesys.core.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class GroupRecordModelExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public GroupRecordModelExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    protected void addCriterionForJDBCDate(String condition, Date value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value.getTime()), property);
    }

    protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
      Iterator<Date> iter = values.iterator();
      while (iter.hasNext()) {
        dateList.add(new java.sql.Date(iter.next().getTime()));
      }
      addCriterion(condition, dateList, property);
    }

    protected void addCriterionForJDBCDate(String condition, Date value1, Date value2,
        String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value1.getTime()),
          new java.sql.Date(value2.getTime()), property);
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNull() {
      addCriterion("created_time is null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNotNull() {
      addCriterion("created_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeEqualTo(Date value) {
      addCriterion("created_time =", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotEqualTo(Date value) {
      addCriterion("created_time <>", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThan(Date value) {
      addCriterion("created_time >", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("created_time >=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThan(Date value) {
      addCriterion("created_time <", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
      addCriterion("created_time <=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIn(List<Date> values) {
      addCriterion("created_time in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotIn(List<Date> values) {
      addCriterion("created_time not in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeBetween(Date value1, Date value2) {
      addCriterion("created_time between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
      addCriterion("created_time not between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNull() {
      addCriterion("modified_time is null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNotNull() {
      addCriterion("modified_time is not null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeEqualTo(Date value) {
      addCriterion("modified_time =", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotEqualTo(Date value) {
      addCriterion("modified_time <>", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThan(Date value) {
      addCriterion("modified_time >", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("modified_time >=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThan(Date value) {
      addCriterion("modified_time <", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
      addCriterion("modified_time <=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIn(List<Date> values) {
      addCriterion("modified_time in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotIn(List<Date> values) {
      addCriterion("modified_time not in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeBetween(Date value1, Date value2) {
      addCriterion("modified_time between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
      addCriterion("modified_time not between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andGroupNameIsNull() {
      addCriterion("group_name is null");
      return (Criteria) this;
    }

    public Criteria andGroupNameIsNotNull() {
      addCriterion("group_name is not null");
      return (Criteria) this;
    }

    public Criteria andGroupNameEqualTo(String value) {
      addCriterion("group_name =", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameNotEqualTo(String value) {
      addCriterion("group_name <>", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameGreaterThan(String value) {
      addCriterion("group_name >", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameGreaterThanOrEqualTo(String value) {
      addCriterion("group_name >=", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameLessThan(String value) {
      addCriterion("group_name <", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameLessThanOrEqualTo(String value) {
      addCriterion("group_name <=", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameLike(String value) {
      addCriterion("group_name like", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameNotLike(String value) {
      addCriterion("group_name not like", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameIn(List<String> values) {
      addCriterion("group_name in", values, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameNotIn(List<String> values) {
      addCriterion("group_name not in", values, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameBetween(String value1, String value2) {
      addCriterion("group_name between", value1, value2, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameNotBetween(String value1, String value2) {
      addCriterion("group_name not between", value1, value2, "groupName");
      return (Criteria) this;
    }

    public Criteria andRecordDateIsNull() {
      addCriterion("record_date is null");
      return (Criteria) this;
    }

    public Criteria andRecordDateIsNotNull() {
      addCriterion("record_date is not null");
      return (Criteria) this;
    }

    public Criteria andRecordDateEqualTo(Date value) {
      addCriterionForJDBCDate("record_date =", value, "recordDate");
      return (Criteria) this;
    }

    public Criteria andRecordDateNotEqualTo(Date value) {
      addCriterionForJDBCDate("record_date <>", value, "recordDate");
      return (Criteria) this;
    }

    public Criteria andRecordDateGreaterThan(Date value) {
      addCriterionForJDBCDate("record_date >", value, "recordDate");
      return (Criteria) this;
    }

    public Criteria andRecordDateGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("record_date >=", value, "recordDate");
      return (Criteria) this;
    }

    public Criteria andRecordDateLessThan(Date value) {
      addCriterionForJDBCDate("record_date <", value, "recordDate");
      return (Criteria) this;
    }

    public Criteria andRecordDateLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("record_date <=", value, "recordDate");
      return (Criteria) this;
    }

    public Criteria andRecordDateIn(List<Date> values) {
      addCriterionForJDBCDate("record_date in", values, "recordDate");
      return (Criteria) this;
    }

    public Criteria andRecordDateNotIn(List<Date> values) {
      addCriterionForJDBCDate("record_date not in", values, "recordDate");
      return (Criteria) this;
    }

    public Criteria andRecordDateBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("record_date between", value1, value2, "recordDate");
      return (Criteria) this;
    }

    public Criteria andRecordDateNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("record_date not between", value1, value2, "recordDate");
      return (Criteria) this;
    }

    public Criteria andScoreIsNull() {
      addCriterion("score is null");
      return (Criteria) this;
    }

    public Criteria andScoreIsNotNull() {
      addCriterion("score is not null");
      return (Criteria) this;
    }

    public Criteria andScoreEqualTo(Byte value) {
      addCriterion("score =", value, "score");
      return (Criteria) this;
    }

    public Criteria andScoreNotEqualTo(Byte value) {
      addCriterion("score <>", value, "score");
      return (Criteria) this;
    }

    public Criteria andScoreGreaterThan(Byte value) {
      addCriterion("score >", value, "score");
      return (Criteria) this;
    }

    public Criteria andScoreGreaterThanOrEqualTo(Byte value) {
      addCriterion("score >=", value, "score");
      return (Criteria) this;
    }

    public Criteria andScoreLessThan(Byte value) {
      addCriterion("score <", value, "score");
      return (Criteria) this;
    }

    public Criteria andScoreLessThanOrEqualTo(Byte value) {
      addCriterion("score <=", value, "score");
      return (Criteria) this;
    }

    public Criteria andScoreIn(List<Byte> values) {
      addCriterion("score in", values, "score");
      return (Criteria) this;
    }

    public Criteria andScoreNotIn(List<Byte> values) {
      addCriterion("score not in", values, "score");
      return (Criteria) this;
    }

    public Criteria andScoreBetween(Byte value1, Byte value2) {
      addCriterion("score between", value1, value2, "score");
      return (Criteria) this;
    }

    public Criteria andScoreNotBetween(Byte value1, Byte value2) {
      addCriterion("score not between", value1, value2, "score");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationIsNull() {
      addCriterion("petition_location is null");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationIsNotNull() {
      addCriterion("petition_location is not null");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationEqualTo(String value) {
      addCriterion("petition_location =", value, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationNotEqualTo(String value) {
      addCriterion("petition_location <>", value, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationGreaterThan(String value) {
      addCriterion("petition_location >", value, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationGreaterThanOrEqualTo(String value) {
      addCriterion("petition_location >=", value, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationLessThan(String value) {
      addCriterion("petition_location <", value, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationLessThanOrEqualTo(String value) {
      addCriterion("petition_location <=", value, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationLike(String value) {
      addCriterion("petition_location like", value, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationNotLike(String value) {
      addCriterion("petition_location not like", value, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationIn(List<String> values) {
      addCriterion("petition_location in", values, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationNotIn(List<String> values) {
      addCriterion("petition_location not in", values, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationBetween(String value1, String value2) {
      addCriterion("petition_location between", value1, value2, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionLocationNotBetween(String value1, String value2) {
      addCriterion("petition_location not between", value1, value2, "petitionLocation");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionIsNull() {
      addCriterion("petition_region is null");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionIsNotNull() {
      addCriterion("petition_region is not null");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionEqualTo(String value) {
      addCriterion("petition_region =", value, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionNotEqualTo(String value) {
      addCriterion("petition_region <>", value, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionGreaterThan(String value) {
      addCriterion("petition_region >", value, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionGreaterThanOrEqualTo(String value) {
      addCriterion("petition_region >=", value, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionLessThan(String value) {
      addCriterion("petition_region <", value, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionLessThanOrEqualTo(String value) {
      addCriterion("petition_region <=", value, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionLike(String value) {
      addCriterion("petition_region like", value, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionNotLike(String value) {
      addCriterion("petition_region not like", value, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionIn(List<String> values) {
      addCriterion("petition_region in", values, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionNotIn(List<String> values) {
      addCriterion("petition_region not in", values, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionBetween(String value1, String value2) {
      addCriterion("petition_region between", value1, value2, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionRegionNotBetween(String value1, String value2) {
      addCriterion("petition_region not between", value1, value2, "petitionRegion");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicIsNull() {
      addCriterion("petition_dynamic is null");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicIsNotNull() {
      addCriterion("petition_dynamic is not null");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicEqualTo(String value) {
      addCriterion("petition_dynamic =", value, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicNotEqualTo(String value) {
      addCriterion("petition_dynamic <>", value, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicGreaterThan(String value) {
      addCriterion("petition_dynamic >", value, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicGreaterThanOrEqualTo(String value) {
      addCriterion("petition_dynamic >=", value, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicLessThan(String value) {
      addCriterion("petition_dynamic <", value, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicLessThanOrEqualTo(String value) {
      addCriterion("petition_dynamic <=", value, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicLike(String value) {
      addCriterion("petition_dynamic like", value, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicNotLike(String value) {
      addCriterion("petition_dynamic not like", value, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicIn(List<String> values) {
      addCriterion("petition_dynamic in", values, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicNotIn(List<String> values) {
      addCriterion("petition_dynamic not in", values, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicBetween(String value1, String value2) {
      addCriterion("petition_dynamic between", value1, value2, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andPetitionDynamicNotBetween(String value1, String value2) {
      addCriterion("petition_dynamic not between", value1, value2, "petitionDynamic");
      return (Criteria) this;
    }

    public Criteria andConfirmIsNull() {
      addCriterion("confirm is null");
      return (Criteria) this;
    }

    public Criteria andConfirmIsNotNull() {
      addCriterion("confirm is not null");
      return (Criteria) this;
    }

    public Criteria andConfirmEqualTo(Boolean value) {
      addCriterion("confirm =", value, "confirm");
      return (Criteria) this;
    }

    public Criteria andConfirmNotEqualTo(Boolean value) {
      addCriterion("confirm <>", value, "confirm");
      return (Criteria) this;
    }

    public Criteria andConfirmGreaterThan(Boolean value) {
      addCriterion("confirm >", value, "confirm");
      return (Criteria) this;
    }

    public Criteria andConfirmGreaterThanOrEqualTo(Boolean value) {
      addCriterion("confirm >=", value, "confirm");
      return (Criteria) this;
    }

    public Criteria andConfirmLessThan(Boolean value) {
      addCriterion("confirm <", value, "confirm");
      return (Criteria) this;
    }

    public Criteria andConfirmLessThanOrEqualTo(Boolean value) {
      addCriterion("confirm <=", value, "confirm");
      return (Criteria) this;
    }

    public Criteria andConfirmIn(List<Boolean> values) {
      addCriterion("confirm in", values, "confirm");
      return (Criteria) this;
    }

    public Criteria andConfirmNotIn(List<Boolean> values) {
      addCriterion("confirm not in", values, "confirm");
      return (Criteria) this;
    }

    public Criteria andConfirmBetween(Boolean value1, Boolean value2) {
      addCriterion("confirm between", value1, value2, "confirm");
      return (Criteria) this;
    }

    public Criteria andConfirmNotBetween(Boolean value1, Boolean value2) {
      addCriterion("confirm not between", value1, value2, "confirm");
      return (Criteria) this;
    }

    public Criteria andInciteMethodIsNull() {
      addCriterion("incite_method is null");
      return (Criteria) this;
    }

    public Criteria andInciteMethodIsNotNull() {
      addCriterion("incite_method is not null");
      return (Criteria) this;
    }

    public Criteria andInciteMethodEqualTo(String value) {
      addCriterion("incite_method =", value, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodNotEqualTo(String value) {
      addCriterion("incite_method <>", value, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodGreaterThan(String value) {
      addCriterion("incite_method >", value, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodGreaterThanOrEqualTo(String value) {
      addCriterion("incite_method >=", value, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodLessThan(String value) {
      addCriterion("incite_method <", value, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodLessThanOrEqualTo(String value) {
      addCriterion("incite_method <=", value, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodLike(String value) {
      addCriterion("incite_method like", value, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodNotLike(String value) {
      addCriterion("incite_method not like", value, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodIn(List<String> values) {
      addCriterion("incite_method in", values, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodNotIn(List<String> values) {
      addCriterion("incite_method not in", values, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodBetween(String value1, String value2) {
      addCriterion("incite_method between", value1, value2, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInciteMethodNotBetween(String value1, String value2) {
      addCriterion("incite_method not between", value1, value2, "inciteMethod");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesIsNull() {
      addCriterion("info_sources is null");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesIsNotNull() {
      addCriterion("info_sources is not null");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesEqualTo(String value) {
      addCriterion("info_sources =", value, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesNotEqualTo(String value) {
      addCriterion("info_sources <>", value, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesGreaterThan(String value) {
      addCriterion("info_sources >", value, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesGreaterThanOrEqualTo(String value) {
      addCriterion("info_sources >=", value, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesLessThan(String value) {
      addCriterion("info_sources <", value, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesLessThanOrEqualTo(String value) {
      addCriterion("info_sources <=", value, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesLike(String value) {
      addCriterion("info_sources like", value, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesNotLike(String value) {
      addCriterion("info_sources not like", value, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesIn(List<String> values) {
      addCriterion("info_sources in", values, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesNotIn(List<String> values) {
      addCriterion("info_sources not in", values, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesBetween(String value1, String value2) {
      addCriterion("info_sources between", value1, value2, "infoSources");
      return (Criteria) this;
    }

    public Criteria andInfoSourcesNotBetween(String value1, String value2) {
      addCriterion("info_sources not between", value1, value2, "infoSources");
      return (Criteria) this;
    }

    public Criteria andActionGroupIsNull() {
      addCriterion("action_group is null");
      return (Criteria) this;
    }

    public Criteria andActionGroupIsNotNull() {
      addCriterion("action_group is not null");
      return (Criteria) this;
    }

    public Criteria andActionGroupEqualTo(String value) {
      addCriterion("action_group =", value, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupNotEqualTo(String value) {
      addCriterion("action_group <>", value, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupGreaterThan(String value) {
      addCriterion("action_group >", value, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupGreaterThanOrEqualTo(String value) {
      addCriterion("action_group >=", value, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupLessThan(String value) {
      addCriterion("action_group <", value, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupLessThanOrEqualTo(String value) {
      addCriterion("action_group <=", value, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupLike(String value) {
      addCriterion("action_group like", value, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupNotLike(String value) {
      addCriterion("action_group not like", value, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupIn(List<String> values) {
      addCriterion("action_group in", values, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupNotIn(List<String> values) {
      addCriterion("action_group not in", values, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupBetween(String value1, String value2) {
      addCriterion("action_group between", value1, value2, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andActionGroupNotBetween(String value1, String value2) {
      addCriterion("action_group not between", value1, value2, "actionGroup");
      return (Criteria) this;
    }

    public Criteria andGroupSizeIsNull() {
      addCriterion("group_size is null");
      return (Criteria) this;
    }

    public Criteria andGroupSizeIsNotNull() {
      addCriterion("group_size is not null");
      return (Criteria) this;
    }

    public Criteria andGroupSizeEqualTo(Short value) {
      addCriterion("group_size =", value, "groupSize");
      return (Criteria) this;
    }

    public Criteria andGroupSizeNotEqualTo(Short value) {
      addCriterion("group_size <>", value, "groupSize");
      return (Criteria) this;
    }

    public Criteria andGroupSizeGreaterThan(Short value) {
      addCriterion("group_size >", value, "groupSize");
      return (Criteria) this;
    }

    public Criteria andGroupSizeGreaterThanOrEqualTo(Short value) {
      addCriterion("group_size >=", value, "groupSize");
      return (Criteria) this;
    }

    public Criteria andGroupSizeLessThan(Short value) {
      addCriterion("group_size <", value, "groupSize");
      return (Criteria) this;
    }

    public Criteria andGroupSizeLessThanOrEqualTo(Short value) {
      addCriterion("group_size <=", value, "groupSize");
      return (Criteria) this;
    }

    public Criteria andGroupSizeIn(List<Short> values) {
      addCriterion("group_size in", values, "groupSize");
      return (Criteria) this;
    }

    public Criteria andGroupSizeNotIn(List<Short> values) {
      addCriterion("group_size not in", values, "groupSize");
      return (Criteria) this;
    }

    public Criteria andGroupSizeBetween(Short value1, Short value2) {
      addCriterion("group_size between", value1, value2, "groupSize");
      return (Criteria) this;
    }

    public Criteria andGroupSizeNotBetween(Short value1, Short value2) {
      addCriterion("group_size not between", value1, value2, "groupSize");
      return (Criteria) this;
    }

    public Criteria andConsequenceIsNull() {
      addCriterion("consequence is null");
      return (Criteria) this;
    }

    public Criteria andConsequenceIsNotNull() {
      addCriterion("consequence is not null");
      return (Criteria) this;
    }

    public Criteria andConsequenceEqualTo(Boolean value) {
      addCriterion("consequence =", value, "consequence");
      return (Criteria) this;
    }

    public Criteria andConsequenceNotEqualTo(Boolean value) {
      addCriterion("consequence <>", value, "consequence");
      return (Criteria) this;
    }

    public Criteria andConsequenceGreaterThan(Boolean value) {
      addCriterion("consequence >", value, "consequence");
      return (Criteria) this;
    }

    public Criteria andConsequenceGreaterThanOrEqualTo(Boolean value) {
      addCriterion("consequence >=", value, "consequence");
      return (Criteria) this;
    }

    public Criteria andConsequenceLessThan(Boolean value) {
      addCriterion("consequence <", value, "consequence");
      return (Criteria) this;
    }

    public Criteria andConsequenceLessThanOrEqualTo(Boolean value) {
      addCriterion("consequence <=", value, "consequence");
      return (Criteria) this;
    }

    public Criteria andConsequenceIn(List<Boolean> values) {
      addCriterion("consequence in", values, "consequence");
      return (Criteria) this;
    }

    public Criteria andConsequenceNotIn(List<Boolean> values) {
      addCriterion("consequence not in", values, "consequence");
      return (Criteria) this;
    }

    public Criteria andConsequenceBetween(Boolean value1, Boolean value2) {
      addCriterion("consequence between", value1, value2, "consequence");
      return (Criteria) this;
    }

    public Criteria andConsequenceNotBetween(Boolean value1, Boolean value2) {
      addCriterion("consequence not between", value1, value2, "consequence");
      return (Criteria) this;
    }

    public Criteria andConseScoreIsNull() {
      addCriterion("conse_score is null");
      return (Criteria) this;
    }

    public Criteria andConseScoreIsNotNull() {
      addCriterion("conse_score is not null");
      return (Criteria) this;
    }

    public Criteria andConseScoreEqualTo(Byte value) {
      addCriterion("conse_score =", value, "conseScore");
      return (Criteria) this;
    }

    public Criteria andConseScoreNotEqualTo(Byte value) {
      addCriterion("conse_score <>", value, "conseScore");
      return (Criteria) this;
    }

    public Criteria andConseScoreGreaterThan(Byte value) {
      addCriterion("conse_score >", value, "conseScore");
      return (Criteria) this;
    }

    public Criteria andConseScoreGreaterThanOrEqualTo(Byte value) {
      addCriterion("conse_score >=", value, "conseScore");
      return (Criteria) this;
    }

    public Criteria andConseScoreLessThan(Byte value) {
      addCriterion("conse_score <", value, "conseScore");
      return (Criteria) this;
    }

    public Criteria andConseScoreLessThanOrEqualTo(Byte value) {
      addCriterion("conse_score <=", value, "conseScore");
      return (Criteria) this;
    }

    public Criteria andConseScoreIn(List<Byte> values) {
      addCriterion("conse_score in", values, "conseScore");
      return (Criteria) this;
    }

    public Criteria andConseScoreNotIn(List<Byte> values) {
      addCriterion("conse_score not in", values, "conseScore");
      return (Criteria) this;
    }

    public Criteria andConseScoreBetween(Byte value1, Byte value2) {
      addCriterion("conse_score between", value1, value2, "conseScore");
      return (Criteria) this;
    }

    public Criteria andConseScoreNotBetween(Byte value1, Byte value2) {
      addCriterion("conse_score not between", value1, value2, "conseScore");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationIsNull() {
      addCriterion("petition_situation is null");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationIsNotNull() {
      addCriterion("petition_situation is not null");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationEqualTo(String value) {
      addCriterion("petition_situation =", value, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationNotEqualTo(String value) {
      addCriterion("petition_situation <>", value, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationGreaterThan(String value) {
      addCriterion("petition_situation >", value, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationGreaterThanOrEqualTo(String value) {
      addCriterion("petition_situation >=", value, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationLessThan(String value) {
      addCriterion("petition_situation <", value, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationLessThanOrEqualTo(String value) {
      addCriterion("petition_situation <=", value, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationLike(String value) {
      addCriterion("petition_situation like", value, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationNotLike(String value) {
      addCriterion("petition_situation not like", value, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationIn(List<String> values) {
      addCriterion("petition_situation in", values, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationNotIn(List<String> values) {
      addCriterion("petition_situation not in", values, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationBetween(String value1, String value2) {
      addCriterion("petition_situation between", value1, value2, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andPetitionSituationNotBetween(String value1, String value2) {
      addCriterion("petition_situation not between", value1, value2, "petitionSituation");
      return (Criteria) this;
    }

    public Criteria andExt1IsNull() {
      addCriterion("ext1 is null");
      return (Criteria) this;
    }

    public Criteria andExt1IsNotNull() {
      addCriterion("ext1 is not null");
      return (Criteria) this;
    }

    public Criteria andExt1EqualTo(String value) {
      addCriterion("ext1 =", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotEqualTo(String value) {
      addCriterion("ext1 <>", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThan(String value) {
      addCriterion("ext1 >", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThanOrEqualTo(String value) {
      addCriterion("ext1 >=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThan(String value) {
      addCriterion("ext1 <", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThanOrEqualTo(String value) {
      addCriterion("ext1 <=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Like(String value) {
      addCriterion("ext1 like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotLike(String value) {
      addCriterion("ext1 not like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1In(List<String> values) {
      addCriterion("ext1 in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotIn(List<String> values) {
      addCriterion("ext1 not in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Between(String value1, String value2) {
      addCriterion("ext1 between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotBetween(String value1, String value2) {
      addCriterion("ext1 not between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt2IsNull() {
      addCriterion("ext2 is null");
      return (Criteria) this;
    }

    public Criteria andExt2IsNotNull() {
      addCriterion("ext2 is not null");
      return (Criteria) this;
    }

    public Criteria andExt2EqualTo(String value) {
      addCriterion("ext2 =", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotEqualTo(String value) {
      addCriterion("ext2 <>", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2GreaterThan(String value) {
      addCriterion("ext2 >", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2GreaterThanOrEqualTo(String value) {
      addCriterion("ext2 >=", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2LessThan(String value) {
      addCriterion("ext2 <", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2LessThanOrEqualTo(String value) {
      addCriterion("ext2 <=", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2Like(String value) {
      addCriterion("ext2 like", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotLike(String value) {
      addCriterion("ext2 not like", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2In(List<String> values) {
      addCriterion("ext2 in", values, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotIn(List<String> values) {
      addCriterion("ext2 not in", values, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2Between(String value1, String value2) {
      addCriterion("ext2 between", value1, value2, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotBetween(String value1, String value2) {
      addCriterion("ext2 not between", value1, value2, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt3IsNull() {
      addCriterion("ext3 is null");
      return (Criteria) this;
    }

    public Criteria andExt3IsNotNull() {
      addCriterion("ext3 is not null");
      return (Criteria) this;
    }

    public Criteria andExt3EqualTo(String value) {
      addCriterion("ext3 =", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotEqualTo(String value) {
      addCriterion("ext3 <>", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3GreaterThan(String value) {
      addCriterion("ext3 >", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3GreaterThanOrEqualTo(String value) {
      addCriterion("ext3 >=", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3LessThan(String value) {
      addCriterion("ext3 <", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3LessThanOrEqualTo(String value) {
      addCriterion("ext3 <=", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3Like(String value) {
      addCriterion("ext3 like", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotLike(String value) {
      addCriterion("ext3 not like", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3In(List<String> values) {
      addCriterion("ext3 in", values, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotIn(List<String> values) {
      addCriterion("ext3 not in", values, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3Between(String value1, String value2) {
      addCriterion("ext3 between", value1, value2, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotBetween(String value1, String value2) {
      addCriterion("ext3 not between", value1, value2, "ext3");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNull() {
      addCriterion("delete_flag is null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNotNull() {
      addCriterion("delete_flag is not null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagEqualTo(Boolean value) {
      addCriterion("delete_flag =", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotEqualTo(Boolean value) {
      addCriterion("delete_flag <>", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThan(Boolean value) {
      addCriterion("delete_flag >", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag >=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThan(Boolean value) {
      addCriterion("delete_flag <", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag <=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIn(List<Boolean> values) {
      addCriterion("delete_flag in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotIn(List<Boolean> values) {
      addCriterion("delete_flag not in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag not between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * group_record
   *
   * @mbg.generated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * group_record
   *
   * @mbg.generated
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}