package cn.qsky.policesys.core.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GroupSummaryModelExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public GroupSummaryModelExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNull() {
      addCriterion("created_time is null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNotNull() {
      addCriterion("created_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeEqualTo(Date value) {
      addCriterion("created_time =", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotEqualTo(Date value) {
      addCriterion("created_time <>", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThan(Date value) {
      addCriterion("created_time >", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("created_time >=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThan(Date value) {
      addCriterion("created_time <", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
      addCriterion("created_time <=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIn(List<Date> values) {
      addCriterion("created_time in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotIn(List<Date> values) {
      addCriterion("created_time not in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeBetween(Date value1, Date value2) {
      addCriterion("created_time between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
      addCriterion("created_time not between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNull() {
      addCriterion("modified_time is null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNotNull() {
      addCriterion("modified_time is not null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeEqualTo(Date value) {
      addCriterion("modified_time =", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotEqualTo(Date value) {
      addCriterion("modified_time <>", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThan(Date value) {
      addCriterion("modified_time >", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("modified_time >=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThan(Date value) {
      addCriterion("modified_time <", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
      addCriterion("modified_time <=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIn(List<Date> values) {
      addCriterion("modified_time in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotIn(List<Date> values) {
      addCriterion("modified_time not in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeBetween(Date value1, Date value2) {
      addCriterion("modified_time between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
      addCriterion("modified_time not between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andGroupNameIsNull() {
      addCriterion("group_name is null");
      return (Criteria) this;
    }

    public Criteria andGroupNameIsNotNull() {
      addCriterion("group_name is not null");
      return (Criteria) this;
    }

    public Criteria andGroupNameEqualTo(String value) {
      addCriterion("group_name =", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameNotEqualTo(String value) {
      addCriterion("group_name <>", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameGreaterThan(String value) {
      addCriterion("group_name >", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameGreaterThanOrEqualTo(String value) {
      addCriterion("group_name >=", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameLessThan(String value) {
      addCriterion("group_name <", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameLessThanOrEqualTo(String value) {
      addCriterion("group_name <=", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameLike(String value) {
      addCriterion("group_name like", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameNotLike(String value) {
      addCriterion("group_name not like", value, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameIn(List<String> values) {
      addCriterion("group_name in", values, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameNotIn(List<String> values) {
      addCriterion("group_name not in", values, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameBetween(String value1, String value2) {
      addCriterion("group_name between", value1, value2, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupNameNotBetween(String value1, String value2) {
      addCriterion("group_name not between", value1, value2, "groupName");
      return (Criteria) this;
    }

    public Criteria andGroupTypeIsNull() {
      addCriterion("group_type is null");
      return (Criteria) this;
    }

    public Criteria andGroupTypeIsNotNull() {
      addCriterion("group_type is not null");
      return (Criteria) this;
    }

    public Criteria andGroupTypeEqualTo(String value) {
      addCriterion("group_type =", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeNotEqualTo(String value) {
      addCriterion("group_type <>", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeGreaterThan(String value) {
      addCriterion("group_type >", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeGreaterThanOrEqualTo(String value) {
      addCriterion("group_type >=", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeLessThan(String value) {
      addCriterion("group_type <", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeLessThanOrEqualTo(String value) {
      addCriterion("group_type <=", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeLike(String value) {
      addCriterion("group_type like", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeNotLike(String value) {
      addCriterion("group_type not like", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeIn(List<String> values) {
      addCriterion("group_type in", values, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeNotIn(List<String> values) {
      addCriterion("group_type not in", values, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeBetween(String value1, String value2) {
      addCriterion("group_type between", value1, value2, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeNotBetween(String value1, String value2) {
      addCriterion("group_type not between", value1, value2, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceIsNull() {
      addCriterion("group_introduce is null");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceIsNotNull() {
      addCriterion("group_introduce is not null");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceEqualTo(String value) {
      addCriterion("group_introduce =", value, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceNotEqualTo(String value) {
      addCriterion("group_introduce <>", value, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceGreaterThan(String value) {
      addCriterion("group_introduce >", value, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceGreaterThanOrEqualTo(String value) {
      addCriterion("group_introduce >=", value, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceLessThan(String value) {
      addCriterion("group_introduce <", value, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceLessThanOrEqualTo(String value) {
      addCriterion("group_introduce <=", value, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceLike(String value) {
      addCriterion("group_introduce like", value, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceNotLike(String value) {
      addCriterion("group_introduce not like", value, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceIn(List<String> values) {
      addCriterion("group_introduce in", values, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceNotIn(List<String> values) {
      addCriterion("group_introduce not in", values, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceBetween(String value1, String value2) {
      addCriterion("group_introduce between", value1, value2, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andGroupIntroduceNotBetween(String value1, String value2) {
      addCriterion("group_introduce not between", value1, value2, "groupIntroduce");
      return (Criteria) this;
    }

    public Criteria andExt1IsNull() {
      addCriterion("ext1 is null");
      return (Criteria) this;
    }

    public Criteria andExt1IsNotNull() {
      addCriterion("ext1 is not null");
      return (Criteria) this;
    }

    public Criteria andExt1EqualTo(String value) {
      addCriterion("ext1 =", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotEqualTo(String value) {
      addCriterion("ext1 <>", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThan(String value) {
      addCriterion("ext1 >", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThanOrEqualTo(String value) {
      addCriterion("ext1 >=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThan(String value) {
      addCriterion("ext1 <", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThanOrEqualTo(String value) {
      addCriterion("ext1 <=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Like(String value) {
      addCriterion("ext1 like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotLike(String value) {
      addCriterion("ext1 not like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1In(List<String> values) {
      addCriterion("ext1 in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotIn(List<String> values) {
      addCriterion("ext1 not in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Between(String value1, String value2) {
      addCriterion("ext1 between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotBetween(String value1, String value2) {
      addCriterion("ext1 not between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNull() {
      addCriterion("delete_flag is null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNotNull() {
      addCriterion("delete_flag is not null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagEqualTo(Boolean value) {
      addCriterion("delete_flag =", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotEqualTo(Boolean value) {
      addCriterion("delete_flag <>", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThan(Boolean value) {
      addCriterion("delete_flag >", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag >=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThan(Boolean value) {
      addCriterion("delete_flag <", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag <=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIn(List<Boolean> values) {
      addCriterion("delete_flag in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotIn(List<Boolean> values) {
      addCriterion("delete_flag not in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag not between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * group_summary
   *
   * @mbg.generated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * group_summary
   *
   * @mbg.generated
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}