package cn.qsky.policesys.core.dao.model;

import java.util.Date;

public class ImportantPersonRecordModel {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.PK
   *
   * @mbg.generated
   */
  private Long pk;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.created_time
   *
   * @mbg.generated
   */
  private Date createdTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.modified_time
   *
   * @mbg.generated
   */
  private Date modifiedTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.name
   *
   * @mbg.generated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.id_card
   *
   * @mbg.generated
   */
  private String idCard;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.score
   *
   * @mbg.generated
   */
  private Byte score;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.record_date
   *
   * @mbg.generated
   */
  private Date recordDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.week
   *
   * @mbg.generated
   */
  private String week;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.group_type
   *
   * @mbg.generated
   */
  private String groupType;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.petition_location
   *
   * @mbg.generated
   */
  private String petitionLocation;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.petition_region
   *
   * @mbg.generated
   */
  private String petitionRegion;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.petition_dynamic
   *
   * @mbg.generated
   */
  private String petitionDynamic;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.confirm
   *
   * @mbg.generated
   */
  private Boolean confirm;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.incite_method
   *
   * @mbg.generated
   */
  private String inciteMethod;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.info_sources
   *
   * @mbg.generated
   */
  private String infoSources;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.qq_group
   *
   * @mbg.generated
   */
  private String qqGroup;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.wechat_group
   *
   * @mbg.generated
   */
  private String wechatGroup;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.group_size
   *
   * @mbg.generated
   */
  private Short groupSize;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.consequence
   *
   * @mbg.generated
   */
  private Boolean consequence;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.conse_score
   *
   * @mbg.generated
   */
  private Byte conseScore;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.petition_situation
   *
   * @mbg.generated
   */
  private String petitionSituation;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.record_type
   *
   * @mbg.generated
   */
  private String recordType;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.ext1
   *
   * @mbg.generated
   */
  private String ext1;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.ext2
   *
   * @mbg.generated
   */
  private String ext2;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.ext3
   *
   * @mbg.generated
   */
  private String ext3;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * important_person_record.delete_flag
   *
   * @mbg.generated
   */
  private Boolean deleteFlag;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.PK
   *
   * @return the value of important_person_record.PK
   * @mbg.generated
   */
  public Long getPk() {
    return pk;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.PK
   *
   * @param pk the value for important_person_record.PK
   * @mbg.generated
   */
  public void setPk(Long pk) {
    this.pk = pk;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.created_time
   *
   * @return the value of important_person_record.created_time
   * @mbg.generated
   */
  public Date getCreatedTime() {
    return createdTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.created_time
   *
   * @param createdTime the value for important_person_record.created_time
   * @mbg.generated
   */
  public void setCreatedTime(Date createdTime) {
    this.createdTime = createdTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.modified_time
   *
   * @return the value of important_person_record.modified_time
   * @mbg.generated
   */
  public Date getModifiedTime() {
    return modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.modified_time
   *
   * @param modifiedTime the value for important_person_record.modified_time
   * @mbg.generated
   */
  public void setModifiedTime(Date modifiedTime) {
    this.modifiedTime = modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.name
   *
   * @return the value of important_person_record.name
   * @mbg.generated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.name
   *
   * @param name the value for important_person_record.name
   * @mbg.generated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.id_card
   *
   * @return the value of important_person_record.id_card
   * @mbg.generated
   */
  public String getIdCard() {
    return idCard;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.id_card
   *
   * @param idCard the value for important_person_record.id_card
   * @mbg.generated
   */
  public void setIdCard(String idCard) {
    this.idCard = idCard == null ? null : idCard.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.score
   *
   * @return the value of important_person_record.score
   * @mbg.generated
   */
  public Byte getScore() {
    return score;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.score
   *
   * @param score the value for important_person_record.score
   * @mbg.generated
   */
  public void setScore(Byte score) {
    this.score = score;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.record_date
   *
   * @return the value of important_person_record.record_date
   * @mbg.generated
   */
  public Date getRecordDate() {
    return recordDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.record_date
   *
   * @param recordDate the value for important_person_record.record_date
   * @mbg.generated
   */
  public void setRecordDate(Date recordDate) {
    this.recordDate = recordDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.week
   *
   * @return the value of important_person_record.week
   * @mbg.generated
   */
  public String getWeek() {
    return week;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.week
   *
   * @param week the value for important_person_record.week
   * @mbg.generated
   */
  public void setWeek(String week) {
    this.week = week == null ? null : week.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.group_type
   *
   * @return the value of important_person_record.group_type
   * @mbg.generated
   */
  public String getGroupType() {
    return groupType;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.group_type
   *
   * @param groupType the value for important_person_record.group_type
   * @mbg.generated
   */
  public void setGroupType(String groupType) {
    this.groupType = groupType == null ? null : groupType.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.petition_location
   *
   * @return the value of important_person_record.petition_location
   * @mbg.generated
   */
  public String getPetitionLocation() {
    return petitionLocation;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.petition_location
   *
   * @param petitionLocation the value for important_person_record.petition_location
   * @mbg.generated
   */
  public void setPetitionLocation(String petitionLocation) {
    this.petitionLocation = petitionLocation == null ? null : petitionLocation.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.petition_region
   *
   * @return the value of important_person_record.petition_region
   * @mbg.generated
   */
  public String getPetitionRegion() {
    return petitionRegion;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.petition_region
   *
   * @param petitionRegion the value for important_person_record.petition_region
   * @mbg.generated
   */
  public void setPetitionRegion(String petitionRegion) {
    this.petitionRegion = petitionRegion == null ? null : petitionRegion.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.petition_dynamic
   *
   * @return the value of important_person_record.petition_dynamic
   * @mbg.generated
   */
  public String getPetitionDynamic() {
    return petitionDynamic;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.petition_dynamic
   *
   * @param petitionDynamic the value for important_person_record.petition_dynamic
   * @mbg.generated
   */
  public void setPetitionDynamic(String petitionDynamic) {
    this.petitionDynamic = petitionDynamic == null ? null : petitionDynamic.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.confirm
   *
   * @return the value of important_person_record.confirm
   * @mbg.generated
   */
  public Boolean getConfirm() {
    return confirm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.confirm
   *
   * @param confirm the value for important_person_record.confirm
   * @mbg.generated
   */
  public void setConfirm(Boolean confirm) {
    this.confirm = confirm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.incite_method
   *
   * @return the value of important_person_record.incite_method
   * @mbg.generated
   */
  public String getInciteMethod() {
    return inciteMethod;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.incite_method
   *
   * @param inciteMethod the value for important_person_record.incite_method
   * @mbg.generated
   */
  public void setInciteMethod(String inciteMethod) {
    this.inciteMethod = inciteMethod == null ? null : inciteMethod.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.info_sources
   *
   * @return the value of important_person_record.info_sources
   * @mbg.generated
   */
  public String getInfoSources() {
    return infoSources;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.info_sources
   *
   * @param infoSources the value for important_person_record.info_sources
   * @mbg.generated
   */
  public void setInfoSources(String infoSources) {
    this.infoSources = infoSources == null ? null : infoSources.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.qq_group
   *
   * @return the value of important_person_record.qq_group
   * @mbg.generated
   */
  public String getQqGroup() {
    return qqGroup;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.qq_group
   *
   * @param qqGroup the value for important_person_record.qq_group
   * @mbg.generated
   */
  public void setQqGroup(String qqGroup) {
    this.qqGroup = qqGroup == null ? null : qqGroup.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.wechat_group
   *
   * @return the value of important_person_record.wechat_group
   * @mbg.generated
   */
  public String getWechatGroup() {
    return wechatGroup;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.wechat_group
   *
   * @param wechatGroup the value for important_person_record.wechat_group
   * @mbg.generated
   */
  public void setWechatGroup(String wechatGroup) {
    this.wechatGroup = wechatGroup == null ? null : wechatGroup.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.group_size
   *
   * @return the value of important_person_record.group_size
   * @mbg.generated
   */
  public Short getGroupSize() {
    return groupSize;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.group_size
   *
   * @param groupSize the value for important_person_record.group_size
   * @mbg.generated
   */
  public void setGroupSize(Short groupSize) {
    this.groupSize = groupSize;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.consequence
   *
   * @return the value of important_person_record.consequence
   * @mbg.generated
   */
  public Boolean getConsequence() {
    return consequence;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.consequence
   *
   * @param consequence the value for important_person_record.consequence
   * @mbg.generated
   */
  public void setConsequence(Boolean consequence) {
    this.consequence = consequence;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.conse_score
   *
   * @return the value of important_person_record.conse_score
   * @mbg.generated
   */
  public Byte getConseScore() {
    return conseScore;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.conse_score
   *
   * @param conseScore the value for important_person_record.conse_score
   * @mbg.generated
   */
  public void setConseScore(Byte conseScore) {
    this.conseScore = conseScore;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.petition_situation
   *
   * @return the value of important_person_record.petition_situation
   * @mbg.generated
   */
  public String getPetitionSituation() {
    return petitionSituation;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.petition_situation
   *
   * @param petitionSituation the value for important_person_record.petition_situation
   * @mbg.generated
   */
  public void setPetitionSituation(String petitionSituation) {
    this.petitionSituation = petitionSituation == null ? null : petitionSituation.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.record_type
   *
   * @return the value of important_person_record.record_type
   * @mbg.generated
   */
  public String getRecordType() {
    return recordType;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.record_type
   *
   * @param recordType the value for important_person_record.record_type
   * @mbg.generated
   */
  public void setRecordType(String recordType) {
    this.recordType = recordType == null ? null : recordType.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.ext1
   *
   * @return the value of important_person_record.ext1
   * @mbg.generated
   */
  public String getExt1() {
    return ext1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.ext1
   *
   * @param ext1 the value for important_person_record.ext1
   * @mbg.generated
   */
  public void setExt1(String ext1) {
    this.ext1 = ext1 == null ? null : ext1.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.ext2
   *
   * @return the value of important_person_record.ext2
   * @mbg.generated
   */
  public String getExt2() {
    return ext2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.ext2
   *
   * @param ext2 the value for important_person_record.ext2
   * @mbg.generated
   */
  public void setExt2(String ext2) {
    this.ext2 = ext2 == null ? null : ext2.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.ext3
   *
   * @return the value of important_person_record.ext3
   * @mbg.generated
   */
  public String getExt3() {
    return ext3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.ext3
   *
   * @param ext3 the value for important_person_record.ext3
   * @mbg.generated
   */
  public void setExt3(String ext3) {
    this.ext3 = ext3 == null ? null : ext3.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column important_person_record.delete_flag
   *
   * @return the value of important_person_record.delete_flag
   * @mbg.generated
   */
  public Boolean getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column important_person_record.delete_flag
   *
   * @param deleteFlag the value for important_person_record.delete_flag
   * @mbg.generated
   */
  public void setDeleteFlag(Boolean deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}