package cn.qsky.policesys.core.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ImportantPersonInfoModelExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public ImportantPersonInfoModelExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNull() {
      addCriterion("created_time is null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNotNull() {
      addCriterion("created_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeEqualTo(Date value) {
      addCriterion("created_time =", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotEqualTo(Date value) {
      addCriterion("created_time <>", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThan(Date value) {
      addCriterion("created_time >", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("created_time >=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThan(Date value) {
      addCriterion("created_time <", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
      addCriterion("created_time <=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIn(List<Date> values) {
      addCriterion("created_time in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotIn(List<Date> values) {
      addCriterion("created_time not in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeBetween(Date value1, Date value2) {
      addCriterion("created_time between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
      addCriterion("created_time not between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNull() {
      addCriterion("modified_time is null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNotNull() {
      addCriterion("modified_time is not null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeEqualTo(Date value) {
      addCriterion("modified_time =", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotEqualTo(Date value) {
      addCriterion("modified_time <>", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThan(Date value) {
      addCriterion("modified_time >", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("modified_time >=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThan(Date value) {
      addCriterion("modified_time <", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
      addCriterion("modified_time <=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIn(List<Date> values) {
      addCriterion("modified_time in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotIn(List<Date> values) {
      addCriterion("modified_time not in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeBetween(Date value1, Date value2) {
      addCriterion("modified_time between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
      addCriterion("modified_time not between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andNameIsNull() {
      addCriterion("name is null");
      return (Criteria) this;
    }

    public Criteria andNameIsNotNull() {
      addCriterion("name is not null");
      return (Criteria) this;
    }

    public Criteria andNameEqualTo(String value) {
      addCriterion("name =", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotEqualTo(String value) {
      addCriterion("name <>", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThan(String value) {
      addCriterion("name >", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThanOrEqualTo(String value) {
      addCriterion("name >=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThan(String value) {
      addCriterion("name <", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThanOrEqualTo(String value) {
      addCriterion("name <=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLike(String value) {
      addCriterion("name like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotLike(String value) {
      addCriterion("name not like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameIn(List<String> values) {
      addCriterion("name in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotIn(List<String> values) {
      addCriterion("name not in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameBetween(String value1, String value2) {
      addCriterion("name between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotBetween(String value1, String value2) {
      addCriterion("name not between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andIdCardIsNull() {
      addCriterion("id_card is null");
      return (Criteria) this;
    }

    public Criteria andIdCardIsNotNull() {
      addCriterion("id_card is not null");
      return (Criteria) this;
    }

    public Criteria andIdCardEqualTo(String value) {
      addCriterion("id_card =", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotEqualTo(String value) {
      addCriterion("id_card <>", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardGreaterThan(String value) {
      addCriterion("id_card >", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardGreaterThanOrEqualTo(String value) {
      addCriterion("id_card >=", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardLessThan(String value) {
      addCriterion("id_card <", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardLessThanOrEqualTo(String value) {
      addCriterion("id_card <=", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardLike(String value) {
      addCriterion("id_card like", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotLike(String value) {
      addCriterion("id_card not like", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardIn(List<String> values) {
      addCriterion("id_card in", values, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotIn(List<String> values) {
      addCriterion("id_card not in", values, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardBetween(String value1, String value2) {
      addCriterion("id_card between", value1, value2, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotBetween(String value1, String value2) {
      addCriterion("id_card not between", value1, value2, "idCard");
      return (Criteria) this;
    }

    public Criteria andSexIsNull() {
      addCriterion("sex is null");
      return (Criteria) this;
    }

    public Criteria andSexIsNotNull() {
      addCriterion("sex is not null");
      return (Criteria) this;
    }

    public Criteria andSexEqualTo(Boolean value) {
      addCriterion("sex =", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexNotEqualTo(Boolean value) {
      addCriterion("sex <>", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexGreaterThan(Boolean value) {
      addCriterion("sex >", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexGreaterThanOrEqualTo(Boolean value) {
      addCriterion("sex >=", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexLessThan(Boolean value) {
      addCriterion("sex <", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexLessThanOrEqualTo(Boolean value) {
      addCriterion("sex <=", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexIn(List<Boolean> values) {
      addCriterion("sex in", values, "sex");
      return (Criteria) this;
    }

    public Criteria andSexNotIn(List<Boolean> values) {
      addCriterion("sex not in", values, "sex");
      return (Criteria) this;
    }

    public Criteria andSexBetween(Boolean value1, Boolean value2) {
      addCriterion("sex between", value1, value2, "sex");
      return (Criteria) this;
    }

    public Criteria andSexNotBetween(Boolean value1, Boolean value2) {
      addCriterion("sex not between", value1, value2, "sex");
      return (Criteria) this;
    }

    public Criteria andNationIsNull() {
      addCriterion("nation is null");
      return (Criteria) this;
    }

    public Criteria andNationIsNotNull() {
      addCriterion("nation is not null");
      return (Criteria) this;
    }

    public Criteria andNationEqualTo(String value) {
      addCriterion("nation =", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationNotEqualTo(String value) {
      addCriterion("nation <>", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationGreaterThan(String value) {
      addCriterion("nation >", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationGreaterThanOrEqualTo(String value) {
      addCriterion("nation >=", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationLessThan(String value) {
      addCriterion("nation <", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationLessThanOrEqualTo(String value) {
      addCriterion("nation <=", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationLike(String value) {
      addCriterion("nation like", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationNotLike(String value) {
      addCriterion("nation not like", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationIn(List<String> values) {
      addCriterion("nation in", values, "nation");
      return (Criteria) this;
    }

    public Criteria andNationNotIn(List<String> values) {
      addCriterion("nation not in", values, "nation");
      return (Criteria) this;
    }

    public Criteria andNationBetween(String value1, String value2) {
      addCriterion("nation between", value1, value2, "nation");
      return (Criteria) this;
    }

    public Criteria andNationNotBetween(String value1, String value2) {
      addCriterion("nation not between", value1, value2, "nation");
      return (Criteria) this;
    }

    public Criteria andAgeIsNull() {
      addCriterion("age is null");
      return (Criteria) this;
    }

    public Criteria andAgeIsNotNull() {
      addCriterion("age is not null");
      return (Criteria) this;
    }

    public Criteria andAgeEqualTo(Byte value) {
      addCriterion("age =", value, "age");
      return (Criteria) this;
    }

    public Criteria andAgeNotEqualTo(Byte value) {
      addCriterion("age <>", value, "age");
      return (Criteria) this;
    }

    public Criteria andAgeGreaterThan(Byte value) {
      addCriterion("age >", value, "age");
      return (Criteria) this;
    }

    public Criteria andAgeGreaterThanOrEqualTo(Byte value) {
      addCriterion("age >=", value, "age");
      return (Criteria) this;
    }

    public Criteria andAgeLessThan(Byte value) {
      addCriterion("age <", value, "age");
      return (Criteria) this;
    }

    public Criteria andAgeLessThanOrEqualTo(Byte value) {
      addCriterion("age <=", value, "age");
      return (Criteria) this;
    }

    public Criteria andAgeIn(List<Byte> values) {
      addCriterion("age in", values, "age");
      return (Criteria) this;
    }

    public Criteria andAgeNotIn(List<Byte> values) {
      addCriterion("age not in", values, "age");
      return (Criteria) this;
    }

    public Criteria andAgeBetween(Byte value1, Byte value2) {
      addCriterion("age between", value1, value2, "age");
      return (Criteria) this;
    }

    public Criteria andAgeNotBetween(Byte value1, Byte value2) {
      addCriterion("age not between", value1, value2, "age");
      return (Criteria) this;
    }

    public Criteria andGroupTypeIsNull() {
      addCriterion("group_type is null");
      return (Criteria) this;
    }

    public Criteria andGroupTypeIsNotNull() {
      addCriterion("group_type is not null");
      return (Criteria) this;
    }

    public Criteria andGroupTypeEqualTo(String value) {
      addCriterion("group_type =", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeNotEqualTo(String value) {
      addCriterion("group_type <>", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeGreaterThan(String value) {
      addCriterion("group_type >", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeGreaterThanOrEqualTo(String value) {
      addCriterion("group_type >=", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeLessThan(String value) {
      addCriterion("group_type <", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeLessThanOrEqualTo(String value) {
      addCriterion("group_type <=", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeLike(String value) {
      addCriterion("group_type like", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeNotLike(String value) {
      addCriterion("group_type not like", value, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeIn(List<String> values) {
      addCriterion("group_type in", values, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeNotIn(List<String> values) {
      addCriterion("group_type not in", values, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeBetween(String value1, String value2) {
      addCriterion("group_type between", value1, value2, "groupType");
      return (Criteria) this;
    }

    public Criteria andGroupTypeNotBetween(String value1, String value2) {
      addCriterion("group_type not between", value1, value2, "groupType");
      return (Criteria) this;
    }

    public Criteria andControlKeywordIsNull() {
      addCriterion("control_keyword is null");
      return (Criteria) this;
    }

    public Criteria andControlKeywordIsNotNull() {
      addCriterion("control_keyword is not null");
      return (Criteria) this;
    }

    public Criteria andControlKeywordEqualTo(String value) {
      addCriterion("control_keyword =", value, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordNotEqualTo(String value) {
      addCriterion("control_keyword <>", value, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordGreaterThan(String value) {
      addCriterion("control_keyword >", value, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordGreaterThanOrEqualTo(String value) {
      addCriterion("control_keyword >=", value, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordLessThan(String value) {
      addCriterion("control_keyword <", value, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordLessThanOrEqualTo(String value) {
      addCriterion("control_keyword <=", value, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordLike(String value) {
      addCriterion("control_keyword like", value, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordNotLike(String value) {
      addCriterion("control_keyword not like", value, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordIn(List<String> values) {
      addCriterion("control_keyword in", values, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordNotIn(List<String> values) {
      addCriterion("control_keyword not in", values, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordBetween(String value1, String value2) {
      addCriterion("control_keyword between", value1, value2, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andControlKeywordNotBetween(String value1, String value2) {
      addCriterion("control_keyword not between", value1, value2, "controlKeyword");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusIsNull() {
      addCriterion("marital_status is null");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusIsNotNull() {
      addCriterion("marital_status is not null");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusEqualTo(String value) {
      addCriterion("marital_status =", value, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusNotEqualTo(String value) {
      addCriterion("marital_status <>", value, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusGreaterThan(String value) {
      addCriterion("marital_status >", value, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusGreaterThanOrEqualTo(String value) {
      addCriterion("marital_status >=", value, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusLessThan(String value) {
      addCriterion("marital_status <", value, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusLessThanOrEqualTo(String value) {
      addCriterion("marital_status <=", value, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusLike(String value) {
      addCriterion("marital_status like", value, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusNotLike(String value) {
      addCriterion("marital_status not like", value, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusIn(List<String> values) {
      addCriterion("marital_status in", values, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusNotIn(List<String> values) {
      addCriterion("marital_status not in", values, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusBetween(String value1, String value2) {
      addCriterion("marital_status between", value1, value2, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andMaritalStatusNotBetween(String value1, String value2) {
      addCriterion("marital_status not between", value1, value2, "maritalStatus");
      return (Criteria) this;
    }

    public Criteria andDomicileIsNull() {
      addCriterion("domicile is null");
      return (Criteria) this;
    }

    public Criteria andDomicileIsNotNull() {
      addCriterion("domicile is not null");
      return (Criteria) this;
    }

    public Criteria andDomicileEqualTo(String value) {
      addCriterion("domicile =", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileNotEqualTo(String value) {
      addCriterion("domicile <>", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileGreaterThan(String value) {
      addCriterion("domicile >", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileGreaterThanOrEqualTo(String value) {
      addCriterion("domicile >=", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileLessThan(String value) {
      addCriterion("domicile <", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileLessThanOrEqualTo(String value) {
      addCriterion("domicile <=", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileLike(String value) {
      addCriterion("domicile like", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileNotLike(String value) {
      addCriterion("domicile not like", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileIn(List<String> values) {
      addCriterion("domicile in", values, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileNotIn(List<String> values) {
      addCriterion("domicile not in", values, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileBetween(String value1, String value2) {
      addCriterion("domicile between", value1, value2, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileNotBetween(String value1, String value2) {
      addCriterion("domicile not between", value1, value2, "domicile");
      return (Criteria) this;
    }

    public Criteria andResidenceIsNull() {
      addCriterion("residence is null");
      return (Criteria) this;
    }

    public Criteria andResidenceIsNotNull() {
      addCriterion("residence is not null");
      return (Criteria) this;
    }

    public Criteria andResidenceEqualTo(String value) {
      addCriterion("residence =", value, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceNotEqualTo(String value) {
      addCriterion("residence <>", value, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceGreaterThan(String value) {
      addCriterion("residence >", value, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceGreaterThanOrEqualTo(String value) {
      addCriterion("residence >=", value, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceLessThan(String value) {
      addCriterion("residence <", value, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceLessThanOrEqualTo(String value) {
      addCriterion("residence <=", value, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceLike(String value) {
      addCriterion("residence like", value, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceNotLike(String value) {
      addCriterion("residence not like", value, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceIn(List<String> values) {
      addCriterion("residence in", values, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceNotIn(List<String> values) {
      addCriterion("residence not in", values, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceBetween(String value1, String value2) {
      addCriterion("residence between", value1, value2, "residence");
      return (Criteria) this;
    }

    public Criteria andResidenceNotBetween(String value1, String value2) {
      addCriterion("residence not between", value1, value2, "residence");
      return (Criteria) this;
    }

    public Criteria andPhoneTextIsNull() {
      addCriterion("phone_text is null");
      return (Criteria) this;
    }

    public Criteria andPhoneTextIsNotNull() {
      addCriterion("phone_text is not null");
      return (Criteria) this;
    }

    public Criteria andPhoneTextEqualTo(String value) {
      addCriterion("phone_text =", value, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextNotEqualTo(String value) {
      addCriterion("phone_text <>", value, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextGreaterThan(String value) {
      addCriterion("phone_text >", value, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextGreaterThanOrEqualTo(String value) {
      addCriterion("phone_text >=", value, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextLessThan(String value) {
      addCriterion("phone_text <", value, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextLessThanOrEqualTo(String value) {
      addCriterion("phone_text <=", value, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextLike(String value) {
      addCriterion("phone_text like", value, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextNotLike(String value) {
      addCriterion("phone_text not like", value, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextIn(List<String> values) {
      addCriterion("phone_text in", values, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextNotIn(List<String> values) {
      addCriterion("phone_text not in", values, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextBetween(String value1, String value2) {
      addCriterion("phone_text between", value1, value2, "phoneText");
      return (Criteria) this;
    }

    public Criteria andPhoneTextNotBetween(String value1, String value2) {
      addCriterion("phone_text not between", value1, value2, "phoneText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextIsNull() {
      addCriterion("wechat_name_text is null");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextIsNotNull() {
      addCriterion("wechat_name_text is not null");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextEqualTo(String value) {
      addCriterion("wechat_name_text =", value, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextNotEqualTo(String value) {
      addCriterion("wechat_name_text <>", value, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextGreaterThan(String value) {
      addCriterion("wechat_name_text >", value, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextGreaterThanOrEqualTo(String value) {
      addCriterion("wechat_name_text >=", value, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextLessThan(String value) {
      addCriterion("wechat_name_text <", value, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextLessThanOrEqualTo(String value) {
      addCriterion("wechat_name_text <=", value, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextLike(String value) {
      addCriterion("wechat_name_text like", value, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextNotLike(String value) {
      addCriterion("wechat_name_text not like", value, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextIn(List<String> values) {
      addCriterion("wechat_name_text in", values, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextNotIn(List<String> values) {
      addCriterion("wechat_name_text not in", values, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextBetween(String value1, String value2) {
      addCriterion("wechat_name_text between", value1, value2, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andWechatNameTextNotBetween(String value1, String value2) {
      addCriterion("wechat_name_text not between", value1, value2, "wechatNameText");
      return (Criteria) this;
    }

    public Criteria andJurisdictionIsNull() {
      addCriterion("jurisdiction is null");
      return (Criteria) this;
    }

    public Criteria andJurisdictionIsNotNull() {
      addCriterion("jurisdiction is not null");
      return (Criteria) this;
    }

    public Criteria andJurisdictionEqualTo(String value) {
      addCriterion("jurisdiction =", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionNotEqualTo(String value) {
      addCriterion("jurisdiction <>", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionGreaterThan(String value) {
      addCriterion("jurisdiction >", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionGreaterThanOrEqualTo(String value) {
      addCriterion("jurisdiction >=", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionLessThan(String value) {
      addCriterion("jurisdiction <", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionLessThanOrEqualTo(String value) {
      addCriterion("jurisdiction <=", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionLike(String value) {
      addCriterion("jurisdiction like", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionNotLike(String value) {
      addCriterion("jurisdiction not like", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionIn(List<String> values) {
      addCriterion("jurisdiction in", values, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionNotIn(List<String> values) {
      addCriterion("jurisdiction not in", values, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionBetween(String value1, String value2) {
      addCriterion("jurisdiction between", value1, value2, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionNotBetween(String value1, String value2) {
      addCriterion("jurisdiction not between", value1, value2, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceIsNull() {
      addCriterion("juri_police is null");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceIsNotNull() {
      addCriterion("juri_police is not null");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceEqualTo(String value) {
      addCriterion("juri_police =", value, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceNotEqualTo(String value) {
      addCriterion("juri_police <>", value, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceGreaterThan(String value) {
      addCriterion("juri_police >", value, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceGreaterThanOrEqualTo(String value) {
      addCriterion("juri_police >=", value, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceLessThan(String value) {
      addCriterion("juri_police <", value, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceLessThanOrEqualTo(String value) {
      addCriterion("juri_police <=", value, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceLike(String value) {
      addCriterion("juri_police like", value, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceNotLike(String value) {
      addCriterion("juri_police not like", value, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceIn(List<String> values) {
      addCriterion("juri_police in", values, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceNotIn(List<String> values) {
      addCriterion("juri_police not in", values, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceBetween(String value1, String value2) {
      addCriterion("juri_police between", value1, value2, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andJuriPoliceNotBetween(String value1, String value2) {
      addCriterion("juri_police not between", value1, value2, "juriPolice");
      return (Criteria) this;
    }

    public Criteria andEducationIsNull() {
      addCriterion("education is null");
      return (Criteria) this;
    }

    public Criteria andEducationIsNotNull() {
      addCriterion("education is not null");
      return (Criteria) this;
    }

    public Criteria andEducationEqualTo(String value) {
      addCriterion("education =", value, "education");
      return (Criteria) this;
    }

    public Criteria andEducationNotEqualTo(String value) {
      addCriterion("education <>", value, "education");
      return (Criteria) this;
    }

    public Criteria andEducationGreaterThan(String value) {
      addCriterion("education >", value, "education");
      return (Criteria) this;
    }

    public Criteria andEducationGreaterThanOrEqualTo(String value) {
      addCriterion("education >=", value, "education");
      return (Criteria) this;
    }

    public Criteria andEducationLessThan(String value) {
      addCriterion("education <", value, "education");
      return (Criteria) this;
    }

    public Criteria andEducationLessThanOrEqualTo(String value) {
      addCriterion("education <=", value, "education");
      return (Criteria) this;
    }

    public Criteria andEducationLike(String value) {
      addCriterion("education like", value, "education");
      return (Criteria) this;
    }

    public Criteria andEducationNotLike(String value) {
      addCriterion("education not like", value, "education");
      return (Criteria) this;
    }

    public Criteria andEducationIn(List<String> values) {
      addCriterion("education in", values, "education");
      return (Criteria) this;
    }

    public Criteria andEducationNotIn(List<String> values) {
      addCriterion("education not in", values, "education");
      return (Criteria) this;
    }

    public Criteria andEducationBetween(String value1, String value2) {
      addCriterion("education between", value1, value2, "education");
      return (Criteria) this;
    }

    public Criteria andEducationNotBetween(String value1, String value2) {
      addCriterion("education not between", value1, value2, "education");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusIsNull() {
      addCriterion("veteran_status is null");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusIsNotNull() {
      addCriterion("veteran_status is not null");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusEqualTo(String value) {
      addCriterion("veteran_status =", value, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusNotEqualTo(String value) {
      addCriterion("veteran_status <>", value, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusGreaterThan(String value) {
      addCriterion("veteran_status >", value, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusGreaterThanOrEqualTo(String value) {
      addCriterion("veteran_status >=", value, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusLessThan(String value) {
      addCriterion("veteran_status <", value, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusLessThanOrEqualTo(String value) {
      addCriterion("veteran_status <=", value, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusLike(String value) {
      addCriterion("veteran_status like", value, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusNotLike(String value) {
      addCriterion("veteran_status not like", value, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusIn(List<String> values) {
      addCriterion("veteran_status in", values, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusNotIn(List<String> values) {
      addCriterion("veteran_status not in", values, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusBetween(String value1, String value2) {
      addCriterion("veteran_status between", value1, value2, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andVeteranStatusNotBetween(String value1, String value2) {
      addCriterion("veteran_status not between", value1, value2, "veteranStatus");
      return (Criteria) this;
    }

    public Criteria andJobIsNull() {
      addCriterion("job is null");
      return (Criteria) this;
    }

    public Criteria andJobIsNotNull() {
      addCriterion("job is not null");
      return (Criteria) this;
    }

    public Criteria andJobEqualTo(String value) {
      addCriterion("job =", value, "job");
      return (Criteria) this;
    }

    public Criteria andJobNotEqualTo(String value) {
      addCriterion("job <>", value, "job");
      return (Criteria) this;
    }

    public Criteria andJobGreaterThan(String value) {
      addCriterion("job >", value, "job");
      return (Criteria) this;
    }

    public Criteria andJobGreaterThanOrEqualTo(String value) {
      addCriterion("job >=", value, "job");
      return (Criteria) this;
    }

    public Criteria andJobLessThan(String value) {
      addCriterion("job <", value, "job");
      return (Criteria) this;
    }

    public Criteria andJobLessThanOrEqualTo(String value) {
      addCriterion("job <=", value, "job");
      return (Criteria) this;
    }

    public Criteria andJobLike(String value) {
      addCriterion("job like", value, "job");
      return (Criteria) this;
    }

    public Criteria andJobNotLike(String value) {
      addCriterion("job not like", value, "job");
      return (Criteria) this;
    }

    public Criteria andJobIn(List<String> values) {
      addCriterion("job in", values, "job");
      return (Criteria) this;
    }

    public Criteria andJobNotIn(List<String> values) {
      addCriterion("job not in", values, "job");
      return (Criteria) this;
    }

    public Criteria andJobBetween(String value1, String value2) {
      addCriterion("job between", value1, value2, "job");
      return (Criteria) this;
    }

    public Criteria andJobNotBetween(String value1, String value2) {
      addCriterion("job not between", value1, value2, "job");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceIsNull() {
      addCriterion("work_place is null");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceIsNotNull() {
      addCriterion("work_place is not null");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceEqualTo(String value) {
      addCriterion("work_place =", value, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceNotEqualTo(String value) {
      addCriterion("work_place <>", value, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceGreaterThan(String value) {
      addCriterion("work_place >", value, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceGreaterThanOrEqualTo(String value) {
      addCriterion("work_place >=", value, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceLessThan(String value) {
      addCriterion("work_place <", value, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceLessThanOrEqualTo(String value) {
      addCriterion("work_place <=", value, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceLike(String value) {
      addCriterion("work_place like", value, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceNotLike(String value) {
      addCriterion("work_place not like", value, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceIn(List<String> values) {
      addCriterion("work_place in", values, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceNotIn(List<String> values) {
      addCriterion("work_place not in", values, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceBetween(String value1, String value2) {
      addCriterion("work_place between", value1, value2, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkPlaceNotBetween(String value1, String value2) {
      addCriterion("work_place not between", value1, value2, "workPlace");
      return (Criteria) this;
    }

    public Criteria andWorkStatusIsNull() {
      addCriterion("work_status is null");
      return (Criteria) this;
    }

    public Criteria andWorkStatusIsNotNull() {
      addCriterion("work_status is not null");
      return (Criteria) this;
    }

    public Criteria andWorkStatusEqualTo(String value) {
      addCriterion("work_status =", value, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusNotEqualTo(String value) {
      addCriterion("work_status <>", value, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusGreaterThan(String value) {
      addCriterion("work_status >", value, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusGreaterThanOrEqualTo(String value) {
      addCriterion("work_status >=", value, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusLessThan(String value) {
      addCriterion("work_status <", value, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusLessThanOrEqualTo(String value) {
      addCriterion("work_status <=", value, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusLike(String value) {
      addCriterion("work_status like", value, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusNotLike(String value) {
      addCriterion("work_status not like", value, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusIn(List<String> values) {
      addCriterion("work_status in", values, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusNotIn(List<String> values) {
      addCriterion("work_status not in", values, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusBetween(String value1, String value2) {
      addCriterion("work_status between", value1, value2, "workStatus");
      return (Criteria) this;
    }

    public Criteria andWorkStatusNotBetween(String value1, String value2) {
      addCriterion("work_status not between", value1, value2, "workStatus");
      return (Criteria) this;
    }

    public Criteria andControlReasonIsNull() {
      addCriterion("control_reason is null");
      return (Criteria) this;
    }

    public Criteria andControlReasonIsNotNull() {
      addCriterion("control_reason is not null");
      return (Criteria) this;
    }

    public Criteria andControlReasonEqualTo(String value) {
      addCriterion("control_reason =", value, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonNotEqualTo(String value) {
      addCriterion("control_reason <>", value, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonGreaterThan(String value) {
      addCriterion("control_reason >", value, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonGreaterThanOrEqualTo(String value) {
      addCriterion("control_reason >=", value, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonLessThan(String value) {
      addCriterion("control_reason <", value, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonLessThanOrEqualTo(String value) {
      addCriterion("control_reason <=", value, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonLike(String value) {
      addCriterion("control_reason like", value, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonNotLike(String value) {
      addCriterion("control_reason not like", value, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonIn(List<String> values) {
      addCriterion("control_reason in", values, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonNotIn(List<String> values) {
      addCriterion("control_reason not in", values, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonBetween(String value1, String value2) {
      addCriterion("control_reason between", value1, value2, "controlReason");
      return (Criteria) this;
    }

    public Criteria andControlReasonNotBetween(String value1, String value2) {
      addCriterion("control_reason not between", value1, value2, "controlReason");
      return (Criteria) this;
    }

    public Criteria andRemarkIsNull() {
      addCriterion("remark is null");
      return (Criteria) this;
    }

    public Criteria andRemarkIsNotNull() {
      addCriterion("remark is not null");
      return (Criteria) this;
    }

    public Criteria andRemarkEqualTo(String value) {
      addCriterion("remark =", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkNotEqualTo(String value) {
      addCriterion("remark <>", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkGreaterThan(String value) {
      addCriterion("remark >", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkGreaterThanOrEqualTo(String value) {
      addCriterion("remark >=", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkLessThan(String value) {
      addCriterion("remark <", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkLessThanOrEqualTo(String value) {
      addCriterion("remark <=", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkLike(String value) {
      addCriterion("remark like", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkNotLike(String value) {
      addCriterion("remark not like", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkIn(List<String> values) {
      addCriterion("remark in", values, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkNotIn(List<String> values) {
      addCriterion("remark not in", values, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkBetween(String value1, String value2) {
      addCriterion("remark between", value1, value2, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkNotBetween(String value1, String value2) {
      addCriterion("remark not between", value1, value2, "remark");
      return (Criteria) this;
    }

    public Criteria andExt1IsNull() {
      addCriterion("ext1 is null");
      return (Criteria) this;
    }

    public Criteria andExt1IsNotNull() {
      addCriterion("ext1 is not null");
      return (Criteria) this;
    }

    public Criteria andExt1EqualTo(String value) {
      addCriterion("ext1 =", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotEqualTo(String value) {
      addCriterion("ext1 <>", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThan(String value) {
      addCriterion("ext1 >", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThanOrEqualTo(String value) {
      addCriterion("ext1 >=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThan(String value) {
      addCriterion("ext1 <", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThanOrEqualTo(String value) {
      addCriterion("ext1 <=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Like(String value) {
      addCriterion("ext1 like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotLike(String value) {
      addCriterion("ext1 not like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1In(List<String> values) {
      addCriterion("ext1 in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotIn(List<String> values) {
      addCriterion("ext1 not in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Between(String value1, String value2) {
      addCriterion("ext1 between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotBetween(String value1, String value2) {
      addCriterion("ext1 not between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt2IsNull() {
      addCriterion("ext2 is null");
      return (Criteria) this;
    }

    public Criteria andExt2IsNotNull() {
      addCriterion("ext2 is not null");
      return (Criteria) this;
    }

    public Criteria andExt2EqualTo(String value) {
      addCriterion("ext2 =", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotEqualTo(String value) {
      addCriterion("ext2 <>", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2GreaterThan(String value) {
      addCriterion("ext2 >", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2GreaterThanOrEqualTo(String value) {
      addCriterion("ext2 >=", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2LessThan(String value) {
      addCriterion("ext2 <", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2LessThanOrEqualTo(String value) {
      addCriterion("ext2 <=", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2Like(String value) {
      addCriterion("ext2 like", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotLike(String value) {
      addCriterion("ext2 not like", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2In(List<String> values) {
      addCriterion("ext2 in", values, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotIn(List<String> values) {
      addCriterion("ext2 not in", values, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2Between(String value1, String value2) {
      addCriterion("ext2 between", value1, value2, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotBetween(String value1, String value2) {
      addCriterion("ext2 not between", value1, value2, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt3IsNull() {
      addCriterion("ext3 is null");
      return (Criteria) this;
    }

    public Criteria andExt3IsNotNull() {
      addCriterion("ext3 is not null");
      return (Criteria) this;
    }

    public Criteria andExt3EqualTo(String value) {
      addCriterion("ext3 =", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotEqualTo(String value) {
      addCriterion("ext3 <>", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3GreaterThan(String value) {
      addCriterion("ext3 >", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3GreaterThanOrEqualTo(String value) {
      addCriterion("ext3 >=", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3LessThan(String value) {
      addCriterion("ext3 <", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3LessThanOrEqualTo(String value) {
      addCriterion("ext3 <=", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3Like(String value) {
      addCriterion("ext3 like", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotLike(String value) {
      addCriterion("ext3 not like", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3In(List<String> values) {
      addCriterion("ext3 in", values, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotIn(List<String> values) {
      addCriterion("ext3 not in", values, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3Between(String value1, String value2) {
      addCriterion("ext3 between", value1, value2, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotBetween(String value1, String value2) {
      addCriterion("ext3 not between", value1, value2, "ext3");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNull() {
      addCriterion("delete_flag is null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNotNull() {
      addCriterion("delete_flag is not null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagEqualTo(Boolean value) {
      addCriterion("delete_flag =", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotEqualTo(Boolean value) {
      addCriterion("delete_flag <>", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThan(Boolean value) {
      addCriterion("delete_flag >", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag >=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThan(Boolean value) {
      addCriterion("delete_flag <", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag <=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIn(List<Boolean> values) {
      addCriterion("delete_flag in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotIn(List<Boolean> values) {
      addCriterion("delete_flag not in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag not between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * important_person_info
   *
   * @mbg.generated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * important_person_info
   *
   * @mbg.generated
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}