package cn.qsky.policesys.core.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PermissionModelExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public PermissionModelExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNull() {
      addCriterion("created_time is null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNotNull() {
      addCriterion("created_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeEqualTo(Date value) {
      addCriterion("created_time =", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotEqualTo(Date value) {
      addCriterion("created_time <>", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThan(Date value) {
      addCriterion("created_time >", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("created_time >=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThan(Date value) {
      addCriterion("created_time <", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
      addCriterion("created_time <=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIn(List<Date> values) {
      addCriterion("created_time in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotIn(List<Date> values) {
      addCriterion("created_time not in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeBetween(Date value1, Date value2) {
      addCriterion("created_time between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
      addCriterion("created_time not between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNull() {
      addCriterion("modified_time is null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNotNull() {
      addCriterion("modified_time is not null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeEqualTo(Date value) {
      addCriterion("modified_time =", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotEqualTo(Date value) {
      addCriterion("modified_time <>", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThan(Date value) {
      addCriterion("modified_time >", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("modified_time >=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThan(Date value) {
      addCriterion("modified_time <", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
      addCriterion("modified_time <=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIn(List<Date> values) {
      addCriterion("modified_time in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotIn(List<Date> values) {
      addCriterion("modified_time not in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeBetween(Date value1, Date value2) {
      addCriterion("modified_time between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
      addCriterion("modified_time not between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andCodeIsNull() {
      addCriterion("code is null");
      return (Criteria) this;
    }

    public Criteria andCodeIsNotNull() {
      addCriterion("code is not null");
      return (Criteria) this;
    }

    public Criteria andCodeEqualTo(String value) {
      addCriterion("code =", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotEqualTo(String value) {
      addCriterion("code <>", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeGreaterThan(String value) {
      addCriterion("code >", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeGreaterThanOrEqualTo(String value) {
      addCriterion("code >=", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLessThan(String value) {
      addCriterion("code <", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLessThanOrEqualTo(String value) {
      addCriterion("code <=", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLike(String value) {
      addCriterion("code like", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotLike(String value) {
      addCriterion("code not like", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeIn(List<String> values) {
      addCriterion("code in", values, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotIn(List<String> values) {
      addCriterion("code not in", values, "code");
      return (Criteria) this;
    }

    public Criteria andCodeBetween(String value1, String value2) {
      addCriterion("code between", value1, value2, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotBetween(String value1, String value2) {
      addCriterion("code not between", value1, value2, "code");
      return (Criteria) this;
    }

    public Criteria andNameIsNull() {
      addCriterion("name is null");
      return (Criteria) this;
    }

    public Criteria andNameIsNotNull() {
      addCriterion("name is not null");
      return (Criteria) this;
    }

    public Criteria andNameEqualTo(String value) {
      addCriterion("name =", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotEqualTo(String value) {
      addCriterion("name <>", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThan(String value) {
      addCriterion("name >", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThanOrEqualTo(String value) {
      addCriterion("name >=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThan(String value) {
      addCriterion("name <", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThanOrEqualTo(String value) {
      addCriterion("name <=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLike(String value) {
      addCriterion("name like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotLike(String value) {
      addCriterion("name not like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameIn(List<String> values) {
      addCriterion("name in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotIn(List<String> values) {
      addCriterion("name not in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameBetween(String value1, String value2) {
      addCriterion("name between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotBetween(String value1, String value2) {
      addCriterion("name not between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andResourcetypeIsNull() {
      addCriterion("resourceType is null");
      return (Criteria) this;
    }

    public Criteria andResourcetypeIsNotNull() {
      addCriterion("resourceType is not null");
      return (Criteria) this;
    }

    public Criteria andResourcetypeEqualTo(String value) {
      addCriterion("resourceType =", value, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeNotEqualTo(String value) {
      addCriterion("resourceType <>", value, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeGreaterThan(String value) {
      addCriterion("resourceType >", value, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeGreaterThanOrEqualTo(String value) {
      addCriterion("resourceType >=", value, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeLessThan(String value) {
      addCriterion("resourceType <", value, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeLessThanOrEqualTo(String value) {
      addCriterion("resourceType <=", value, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeLike(String value) {
      addCriterion("resourceType like", value, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeNotLike(String value) {
      addCriterion("resourceType not like", value, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeIn(List<String> values) {
      addCriterion("resourceType in", values, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeNotIn(List<String> values) {
      addCriterion("resourceType not in", values, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeBetween(String value1, String value2) {
      addCriterion("resourceType between", value1, value2, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andResourcetypeNotBetween(String value1, String value2) {
      addCriterion("resourceType not between", value1, value2, "resourcetype");
      return (Criteria) this;
    }

    public Criteria andUrlIsNull() {
      addCriterion("url is null");
      return (Criteria) this;
    }

    public Criteria andUrlIsNotNull() {
      addCriterion("url is not null");
      return (Criteria) this;
    }

    public Criteria andUrlEqualTo(String value) {
      addCriterion("url =", value, "url");
      return (Criteria) this;
    }

    public Criteria andUrlNotEqualTo(String value) {
      addCriterion("url <>", value, "url");
      return (Criteria) this;
    }

    public Criteria andUrlGreaterThan(String value) {
      addCriterion("url >", value, "url");
      return (Criteria) this;
    }

    public Criteria andUrlGreaterThanOrEqualTo(String value) {
      addCriterion("url >=", value, "url");
      return (Criteria) this;
    }

    public Criteria andUrlLessThan(String value) {
      addCriterion("url <", value, "url");
      return (Criteria) this;
    }

    public Criteria andUrlLessThanOrEqualTo(String value) {
      addCriterion("url <=", value, "url");
      return (Criteria) this;
    }

    public Criteria andUrlLike(String value) {
      addCriterion("url like", value, "url");
      return (Criteria) this;
    }

    public Criteria andUrlNotLike(String value) {
      addCriterion("url not like", value, "url");
      return (Criteria) this;
    }

    public Criteria andUrlIn(List<String> values) {
      addCriterion("url in", values, "url");
      return (Criteria) this;
    }

    public Criteria andUrlNotIn(List<String> values) {
      addCriterion("url not in", values, "url");
      return (Criteria) this;
    }

    public Criteria andUrlBetween(String value1, String value2) {
      addCriterion("url between", value1, value2, "url");
      return (Criteria) this;
    }

    public Criteria andUrlNotBetween(String value1, String value2) {
      addCriterion("url not between", value1, value2, "url");
      return (Criteria) this;
    }

    public Criteria andPermissionIsNull() {
      addCriterion("permission is null");
      return (Criteria) this;
    }

    public Criteria andPermissionIsNotNull() {
      addCriterion("permission is not null");
      return (Criteria) this;
    }

    public Criteria andPermissionEqualTo(String value) {
      addCriterion("permission =", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionNotEqualTo(String value) {
      addCriterion("permission <>", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionGreaterThan(String value) {
      addCriterion("permission >", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionGreaterThanOrEqualTo(String value) {
      addCriterion("permission >=", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionLessThan(String value) {
      addCriterion("permission <", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionLessThanOrEqualTo(String value) {
      addCriterion("permission <=", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionLike(String value) {
      addCriterion("permission like", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionNotLike(String value) {
      addCriterion("permission not like", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionIn(List<String> values) {
      addCriterion("permission in", values, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionNotIn(List<String> values) {
      addCriterion("permission not in", values, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionBetween(String value1, String value2) {
      addCriterion("permission between", value1, value2, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionNotBetween(String value1, String value2) {
      addCriterion("permission not between", value1, value2, "permission");
      return (Criteria) this;
    }

    public Criteria andParentIsNull() {
      addCriterion("parent is null");
      return (Criteria) this;
    }

    public Criteria andParentIsNotNull() {
      addCriterion("parent is not null");
      return (Criteria) this;
    }

    public Criteria andParentEqualTo(Long value) {
      addCriterion("parent =", value, "parent");
      return (Criteria) this;
    }

    public Criteria andParentNotEqualTo(Long value) {
      addCriterion("parent <>", value, "parent");
      return (Criteria) this;
    }

    public Criteria andParentGreaterThan(Long value) {
      addCriterion("parent >", value, "parent");
      return (Criteria) this;
    }

    public Criteria andParentGreaterThanOrEqualTo(Long value) {
      addCriterion("parent >=", value, "parent");
      return (Criteria) this;
    }

    public Criteria andParentLessThan(Long value) {
      addCriterion("parent <", value, "parent");
      return (Criteria) this;
    }

    public Criteria andParentLessThanOrEqualTo(Long value) {
      addCriterion("parent <=", value, "parent");
      return (Criteria) this;
    }

    public Criteria andParentIn(List<Long> values) {
      addCriterion("parent in", values, "parent");
      return (Criteria) this;
    }

    public Criteria andParentNotIn(List<Long> values) {
      addCriterion("parent not in", values, "parent");
      return (Criteria) this;
    }

    public Criteria andParentBetween(Long value1, Long value2) {
      addCriterion("parent between", value1, value2, "parent");
      return (Criteria) this;
    }

    public Criteria andParentNotBetween(Long value1, Long value2) {
      addCriterion("parent not between", value1, value2, "parent");
      return (Criteria) this;
    }

    public Criteria andExt1IsNull() {
      addCriterion("ext1 is null");
      return (Criteria) this;
    }

    public Criteria andExt1IsNotNull() {
      addCriterion("ext1 is not null");
      return (Criteria) this;
    }

    public Criteria andExt1EqualTo(String value) {
      addCriterion("ext1 =", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotEqualTo(String value) {
      addCriterion("ext1 <>", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThan(String value) {
      addCriterion("ext1 >", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThanOrEqualTo(String value) {
      addCriterion("ext1 >=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThan(String value) {
      addCriterion("ext1 <", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThanOrEqualTo(String value) {
      addCriterion("ext1 <=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Like(String value) {
      addCriterion("ext1 like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotLike(String value) {
      addCriterion("ext1 not like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1In(List<String> values) {
      addCriterion("ext1 in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotIn(List<String> values) {
      addCriterion("ext1 not in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Between(String value1, String value2) {
      addCriterion("ext1 between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotBetween(String value1, String value2) {
      addCriterion("ext1 not between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt2IsNull() {
      addCriterion("ext2 is null");
      return (Criteria) this;
    }

    public Criteria andExt2IsNotNull() {
      addCriterion("ext2 is not null");
      return (Criteria) this;
    }

    public Criteria andExt2EqualTo(String value) {
      addCriterion("ext2 =", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotEqualTo(String value) {
      addCriterion("ext2 <>", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2GreaterThan(String value) {
      addCriterion("ext2 >", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2GreaterThanOrEqualTo(String value) {
      addCriterion("ext2 >=", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2LessThan(String value) {
      addCriterion("ext2 <", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2LessThanOrEqualTo(String value) {
      addCriterion("ext2 <=", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2Like(String value) {
      addCriterion("ext2 like", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotLike(String value) {
      addCriterion("ext2 not like", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2In(List<String> values) {
      addCriterion("ext2 in", values, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotIn(List<String> values) {
      addCriterion("ext2 not in", values, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2Between(String value1, String value2) {
      addCriterion("ext2 between", value1, value2, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotBetween(String value1, String value2) {
      addCriterion("ext2 not between", value1, value2, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt3IsNull() {
      addCriterion("ext3 is null");
      return (Criteria) this;
    }

    public Criteria andExt3IsNotNull() {
      addCriterion("ext3 is not null");
      return (Criteria) this;
    }

    public Criteria andExt3EqualTo(String value) {
      addCriterion("ext3 =", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotEqualTo(String value) {
      addCriterion("ext3 <>", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3GreaterThan(String value) {
      addCriterion("ext3 >", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3GreaterThanOrEqualTo(String value) {
      addCriterion("ext3 >=", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3LessThan(String value) {
      addCriterion("ext3 <", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3LessThanOrEqualTo(String value) {
      addCriterion("ext3 <=", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3Like(String value) {
      addCriterion("ext3 like", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotLike(String value) {
      addCriterion("ext3 not like", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3In(List<String> values) {
      addCriterion("ext3 in", values, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotIn(List<String> values) {
      addCriterion("ext3 not in", values, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3Between(String value1, String value2) {
      addCriterion("ext3 between", value1, value2, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotBetween(String value1, String value2) {
      addCriterion("ext3 not between", value1, value2, "ext3");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNull() {
      addCriterion("delete_flag is null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNotNull() {
      addCriterion("delete_flag is not null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagEqualTo(Boolean value) {
      addCriterion("delete_flag =", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotEqualTo(Boolean value) {
      addCriterion("delete_flag <>", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThan(Boolean value) {
      addCriterion("delete_flag >", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag >=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThan(Boolean value) {
      addCriterion("delete_flag <", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag <=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIn(List<Boolean> values) {
      addCriterion("delete_flag in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotIn(List<Boolean> values) {
      addCriterion("delete_flag not in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag not between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * permission
   *
   * @mbg.generated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * permission
   *
   * @mbg.generated
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}