package cn.qsky.policesys.core.dao.model;

import java.util.Date;

public class PersonContactInfoModel {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person_contact_info.PK
   *
   * @mbg.generated
   */
  private Long pk;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person_contact_info.created_time
   *
   * @mbg.generated
   */
  private Date createdTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person_contact_info.modified_time
   *
   * @mbg.generated
   */
  private Date modifiedTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person_contact_info.person_pk
   *
   * @mbg.generated
   */
  private Long personPk;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person_contact_info.phone
   *
   * @mbg.generated
   */
  private String phone;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person_contact_info.wechat_name
   *
   * @mbg.generated
   */
  private String wechatName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person_contact_info.ext1
   *
   * @mbg.generated
   */
  private String ext1;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person_contact_info.delete_flag
   *
   * @mbg.generated
   */
  private Boolean deleteFlag;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person_contact_info.PK
   *
   * @return the value of person_contact_info.PK
   * @mbg.generated
   */
  public Long getPk() {
    return pk;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person_contact_info.PK
   *
   * @param pk the value for person_contact_info.PK
   * @mbg.generated
   */
  public void setPk(Long pk) {
    this.pk = pk;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person_contact_info.created_time
   *
   * @return the value of person_contact_info.created_time
   * @mbg.generated
   */
  public Date getCreatedTime() {
    return createdTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person_contact_info.created_time
   *
   * @param createdTime the value for person_contact_info.created_time
   * @mbg.generated
   */
  public void setCreatedTime(Date createdTime) {
    this.createdTime = createdTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person_contact_info.modified_time
   *
   * @return the value of person_contact_info.modified_time
   * @mbg.generated
   */
  public Date getModifiedTime() {
    return modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person_contact_info.modified_time
   *
   * @param modifiedTime the value for person_contact_info.modified_time
   * @mbg.generated
   */
  public void setModifiedTime(Date modifiedTime) {
    this.modifiedTime = modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person_contact_info.person_pk
   *
   * @return the value of person_contact_info.person_pk
   * @mbg.generated
   */
  public Long getPersonPk() {
    return personPk;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person_contact_info.person_pk
   *
   * @param personPk the value for person_contact_info.person_pk
   * @mbg.generated
   */
  public void setPersonPk(Long personPk) {
    this.personPk = personPk;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person_contact_info.phone
   *
   * @return the value of person_contact_info.phone
   * @mbg.generated
   */
  public String getPhone() {
    return phone;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person_contact_info.phone
   *
   * @param phone the value for person_contact_info.phone
   * @mbg.generated
   */
  public void setPhone(String phone) {
    this.phone = phone == null ? null : phone.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person_contact_info.wechat_name
   *
   * @return the value of person_contact_info.wechat_name
   * @mbg.generated
   */
  public String getWechatName() {
    return wechatName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person_contact_info.wechat_name
   *
   * @param wechatName the value for person_contact_info.wechat_name
   * @mbg.generated
   */
  public void setWechatName(String wechatName) {
    this.wechatName = wechatName == null ? null : wechatName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person_contact_info.ext1
   *
   * @return the value of person_contact_info.ext1
   * @mbg.generated
   */
  public String getExt1() {
    return ext1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person_contact_info.ext1
   *
   * @param ext1 the value for person_contact_info.ext1
   * @mbg.generated
   */
  public void setExt1(String ext1) {
    this.ext1 = ext1 == null ? null : ext1.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person_contact_info.delete_flag
   *
   * @return the value of person_contact_info.delete_flag
   * @mbg.generated
   */
  public Boolean getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person_contact_info.delete_flag
   *
   * @param deleteFlag the value for person_contact_info.delete_flag
   * @mbg.generated
   */
  public void setDeleteFlag(Boolean deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}