package cn.qsky.policesys.core.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PersonContactInfoModelExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public PersonContactInfoModelExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNull() {
      addCriterion("created_time is null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNotNull() {
      addCriterion("created_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeEqualTo(Date value) {
      addCriterion("created_time =", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotEqualTo(Date value) {
      addCriterion("created_time <>", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThan(Date value) {
      addCriterion("created_time >", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("created_time >=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThan(Date value) {
      addCriterion("created_time <", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
      addCriterion("created_time <=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIn(List<Date> values) {
      addCriterion("created_time in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotIn(List<Date> values) {
      addCriterion("created_time not in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeBetween(Date value1, Date value2) {
      addCriterion("created_time between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
      addCriterion("created_time not between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNull() {
      addCriterion("modified_time is null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNotNull() {
      addCriterion("modified_time is not null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeEqualTo(Date value) {
      addCriterion("modified_time =", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotEqualTo(Date value) {
      addCriterion("modified_time <>", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThan(Date value) {
      addCriterion("modified_time >", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("modified_time >=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThan(Date value) {
      addCriterion("modified_time <", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
      addCriterion("modified_time <=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIn(List<Date> values) {
      addCriterion("modified_time in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotIn(List<Date> values) {
      addCriterion("modified_time not in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeBetween(Date value1, Date value2) {
      addCriterion("modified_time between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
      addCriterion("modified_time not between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andPersonPkIsNull() {
      addCriterion("person_pk is null");
      return (Criteria) this;
    }

    public Criteria andPersonPkIsNotNull() {
      addCriterion("person_pk is not null");
      return (Criteria) this;
    }

    public Criteria andPersonPkEqualTo(Long value) {
      addCriterion("person_pk =", value, "personPk");
      return (Criteria) this;
    }

    public Criteria andPersonPkNotEqualTo(Long value) {
      addCriterion("person_pk <>", value, "personPk");
      return (Criteria) this;
    }

    public Criteria andPersonPkGreaterThan(Long value) {
      addCriterion("person_pk >", value, "personPk");
      return (Criteria) this;
    }

    public Criteria andPersonPkGreaterThanOrEqualTo(Long value) {
      addCriterion("person_pk >=", value, "personPk");
      return (Criteria) this;
    }

    public Criteria andPersonPkLessThan(Long value) {
      addCriterion("person_pk <", value, "personPk");
      return (Criteria) this;
    }

    public Criteria andPersonPkLessThanOrEqualTo(Long value) {
      addCriterion("person_pk <=", value, "personPk");
      return (Criteria) this;
    }

    public Criteria andPersonPkIn(List<Long> values) {
      addCriterion("person_pk in", values, "personPk");
      return (Criteria) this;
    }

    public Criteria andPersonPkNotIn(List<Long> values) {
      addCriterion("person_pk not in", values, "personPk");
      return (Criteria) this;
    }

    public Criteria andPersonPkBetween(Long value1, Long value2) {
      addCriterion("person_pk between", value1, value2, "personPk");
      return (Criteria) this;
    }

    public Criteria andPersonPkNotBetween(Long value1, Long value2) {
      addCriterion("person_pk not between", value1, value2, "personPk");
      return (Criteria) this;
    }

    public Criteria andPhoneIsNull() {
      addCriterion("phone is null");
      return (Criteria) this;
    }

    public Criteria andPhoneIsNotNull() {
      addCriterion("phone is not null");
      return (Criteria) this;
    }

    public Criteria andPhoneEqualTo(String value) {
      addCriterion("phone =", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneNotEqualTo(String value) {
      addCriterion("phone <>", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneGreaterThan(String value) {
      addCriterion("phone >", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneGreaterThanOrEqualTo(String value) {
      addCriterion("phone >=", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneLessThan(String value) {
      addCriterion("phone <", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneLessThanOrEqualTo(String value) {
      addCriterion("phone <=", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneLike(String value) {
      addCriterion("phone like", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneNotLike(String value) {
      addCriterion("phone not like", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneIn(List<String> values) {
      addCriterion("phone in", values, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneNotIn(List<String> values) {
      addCriterion("phone not in", values, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneBetween(String value1, String value2) {
      addCriterion("phone between", value1, value2, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneNotBetween(String value1, String value2) {
      addCriterion("phone not between", value1, value2, "phone");
      return (Criteria) this;
    }

    public Criteria andWechatNameIsNull() {
      addCriterion("wechat_name is null");
      return (Criteria) this;
    }

    public Criteria andWechatNameIsNotNull() {
      addCriterion("wechat_name is not null");
      return (Criteria) this;
    }

    public Criteria andWechatNameEqualTo(String value) {
      addCriterion("wechat_name =", value, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameNotEqualTo(String value) {
      addCriterion("wechat_name <>", value, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameGreaterThan(String value) {
      addCriterion("wechat_name >", value, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameGreaterThanOrEqualTo(String value) {
      addCriterion("wechat_name >=", value, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameLessThan(String value) {
      addCriterion("wechat_name <", value, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameLessThanOrEqualTo(String value) {
      addCriterion("wechat_name <=", value, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameLike(String value) {
      addCriterion("wechat_name like", value, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameNotLike(String value) {
      addCriterion("wechat_name not like", value, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameIn(List<String> values) {
      addCriterion("wechat_name in", values, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameNotIn(List<String> values) {
      addCriterion("wechat_name not in", values, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameBetween(String value1, String value2) {
      addCriterion("wechat_name between", value1, value2, "wechatName");
      return (Criteria) this;
    }

    public Criteria andWechatNameNotBetween(String value1, String value2) {
      addCriterion("wechat_name not between", value1, value2, "wechatName");
      return (Criteria) this;
    }

    public Criteria andExt1IsNull() {
      addCriterion("ext1 is null");
      return (Criteria) this;
    }

    public Criteria andExt1IsNotNull() {
      addCriterion("ext1 is not null");
      return (Criteria) this;
    }

    public Criteria andExt1EqualTo(String value) {
      addCriterion("ext1 =", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotEqualTo(String value) {
      addCriterion("ext1 <>", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThan(String value) {
      addCriterion("ext1 >", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThanOrEqualTo(String value) {
      addCriterion("ext1 >=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThan(String value) {
      addCriterion("ext1 <", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThanOrEqualTo(String value) {
      addCriterion("ext1 <=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Like(String value) {
      addCriterion("ext1 like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotLike(String value) {
      addCriterion("ext1 not like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1In(List<String> values) {
      addCriterion("ext1 in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotIn(List<String> values) {
      addCriterion("ext1 not in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Between(String value1, String value2) {
      addCriterion("ext1 between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotBetween(String value1, String value2) {
      addCriterion("ext1 not between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNull() {
      addCriterion("delete_flag is null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNotNull() {
      addCriterion("delete_flag is not null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagEqualTo(Boolean value) {
      addCriterion("delete_flag =", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotEqualTo(Boolean value) {
      addCriterion("delete_flag <>", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThan(Boolean value) {
      addCriterion("delete_flag >", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag >=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThan(Boolean value) {
      addCriterion("delete_flag <", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag <=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIn(List<Boolean> values) {
      addCriterion("delete_flag in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotIn(List<Boolean> values) {
      addCriterion("delete_flag not in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag not between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * person_contact_info
   *
   * @mbg.generated
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}