package cn.qsky.policesys.core.dao.model;

import java.util.Date;

public class SpecialPersonModel {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.PK
   *
   * @mbg.generated
   */
  private Long pk;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.created_time
   *
   * @mbg.generated
   */
  private Date createdTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.modified_time
   *
   * @mbg.generated
   */
  private Date modifiedTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.name
   *
   * @mbg.generated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.id_card
   *
   * @mbg.generated
   */
  private String idCard;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.phone
   *
   * @mbg.generated
   */
  private String phone;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.jurisdiction
   *
   * @mbg.generated
   */
  private String jurisdiction;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.resource_name
   *
   * @mbg.generated
   */
  private String resourceName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.activity_place
   *
   * @mbg.generated
   */
  private String activityPlace;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.activity_place_detail
   *
   * @mbg.generated
   */
  private String activityPlaceDetail;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.activity_time
   *
   * @mbg.generated
   */
  private Date activityTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.push_time
   *
   * @mbg.generated
   */
  private Date pushTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.domicile
   *
   * @mbg.generated
   */
  private String domicile;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.person_type
   *
   * @mbg.generated
   */
  private Boolean personType;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.nation
   *
   * @mbg.generated
   */
  private String nation;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.stay_internet_site
   *
   * @mbg.generated
   */
  private String stayInternetSite;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.tj_time_reason
   *
   * @mbg.generated
   */
  private String tjTimeReason;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.vehicle
   *
   * @mbg.generated
   */
  private String vehicle;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.tj_stay_site
   *
   * @mbg.generated
   */
  private String tjStaySite;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.tj_contact
   *
   * @mbg.generated
   */
  private String tjContact;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.belongings
   *
   * @mbg.generated
   */
  private String belongings;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.virtual_identity
   *
   * @mbg.generated
   */
  private String virtualIdentity;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.peer_staff
   *
   * @mbg.generated
   */
  private String peerStaff;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.stay_staff
   *
   * @mbg.generated
   */
  private String stayStaff;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.car_num
   *
   * @mbg.generated
   */
  private String carNum;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.terrorist_char
   *
   * @mbg.generated
   */
  private String terroristChar;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.control_type
   *
   * @mbg.generated
   */
  private String controlType;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.check_site
   *
   * @mbg.generated
   */
  private String checkSite;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.check_police
   *
   * @mbg.generated
   */
  private String checkPolice;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.ext1
   *
   * @mbg.generated
   */
  private String ext1;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.ext2
   *
   * @mbg.generated
   */
  private String ext2;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.ext3
   *
   * @mbg.generated
   */
  private String ext3;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * special_person.delete_flag
   *
   * @mbg.generated
   */
  private Boolean deleteFlag;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.PK
   *
   * @return the value of special_person.PK
   * @mbg.generated
   */
  public Long getPk() {
    return pk;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.PK
   *
   * @param pk the value for special_person.PK
   * @mbg.generated
   */
  public void setPk(Long pk) {
    this.pk = pk;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.created_time
   *
   * @return the value of special_person.created_time
   * @mbg.generated
   */
  public Date getCreatedTime() {
    return createdTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.created_time
   *
   * @param createdTime the value for special_person.created_time
   * @mbg.generated
   */
  public void setCreatedTime(Date createdTime) {
    this.createdTime = createdTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.modified_time
   *
   * @return the value of special_person.modified_time
   * @mbg.generated
   */
  public Date getModifiedTime() {
    return modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.modified_time
   *
   * @param modifiedTime the value for special_person.modified_time
   * @mbg.generated
   */
  public void setModifiedTime(Date modifiedTime) {
    this.modifiedTime = modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.name
   *
   * @return the value of special_person.name
   * @mbg.generated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.name
   *
   * @param name the value for special_person.name
   * @mbg.generated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.id_card
   *
   * @return the value of special_person.id_card
   * @mbg.generated
   */
  public String getIdCard() {
    return idCard;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.id_card
   *
   * @param idCard the value for special_person.id_card
   * @mbg.generated
   */
  public void setIdCard(String idCard) {
    this.idCard = idCard == null ? null : idCard.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.phone
   *
   * @return the value of special_person.phone
   * @mbg.generated
   */
  public String getPhone() {
    return phone;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.phone
   *
   * @param phone the value for special_person.phone
   * @mbg.generated
   */
  public void setPhone(String phone) {
    this.phone = phone == null ? null : phone.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.jurisdiction
   *
   * @return the value of special_person.jurisdiction
   * @mbg.generated
   */
  public String getJurisdiction() {
    return jurisdiction;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.jurisdiction
   *
   * @param jurisdiction the value for special_person.jurisdiction
   * @mbg.generated
   */
  public void setJurisdiction(String jurisdiction) {
    this.jurisdiction = jurisdiction == null ? null : jurisdiction.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.resource_name
   *
   * @return the value of special_person.resource_name
   * @mbg.generated
   */
  public String getResourceName() {
    return resourceName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.resource_name
   *
   * @param resourceName the value for special_person.resource_name
   * @mbg.generated
   */
  public void setResourceName(String resourceName) {
    this.resourceName = resourceName == null ? null : resourceName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.activity_place
   *
   * @return the value of special_person.activity_place
   * @mbg.generated
   */
  public String getActivityPlace() {
    return activityPlace;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.activity_place
   *
   * @param activityPlace the value for special_person.activity_place
   * @mbg.generated
   */
  public void setActivityPlace(String activityPlace) {
    this.activityPlace = activityPlace == null ? null : activityPlace.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.activity_place_detail
   *
   * @return the value of special_person.activity_place_detail
   * @mbg.generated
   */
  public String getActivityPlaceDetail() {
    return activityPlaceDetail;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.activity_place_detail
   *
   * @param activityPlaceDetail the value for special_person.activity_place_detail
   * @mbg.generated
   */
  public void setActivityPlaceDetail(String activityPlaceDetail) {
    this.activityPlaceDetail = activityPlaceDetail == null ? null : activityPlaceDetail.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.activity_time
   *
   * @return the value of special_person.activity_time
   * @mbg.generated
   */
  public Date getActivityTime() {
    return activityTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.activity_time
   *
   * @param activityTime the value for special_person.activity_time
   * @mbg.generated
   */
  public void setActivityTime(Date activityTime) {
    this.activityTime = activityTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.push_time
   *
   * @return the value of special_person.push_time
   * @mbg.generated
   */
  public Date getPushTime() {
    return pushTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.push_time
   *
   * @param pushTime the value for special_person.push_time
   * @mbg.generated
   */
  public void setPushTime(Date pushTime) {
    this.pushTime = pushTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.domicile
   *
   * @return the value of special_person.domicile
   * @mbg.generated
   */
  public String getDomicile() {
    return domicile;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.domicile
   *
   * @param domicile the value for special_person.domicile
   * @mbg.generated
   */
  public void setDomicile(String domicile) {
    this.domicile = domicile == null ? null : domicile.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.person_type
   *
   * @return the value of special_person.person_type
   * @mbg.generated
   */
  public Boolean getPersonType() {
    return personType;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.person_type
   *
   * @param personType the value for special_person.person_type
   * @mbg.generated
   */
  public void setPersonType(Boolean personType) {
    this.personType = personType;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.nation
   *
   * @return the value of special_person.nation
   * @mbg.generated
   */
  public String getNation() {
    return nation;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.nation
   *
   * @param nation the value for special_person.nation
   * @mbg.generated
   */
  public void setNation(String nation) {
    this.nation = nation == null ? null : nation.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.stay_internet_site
   *
   * @return the value of special_person.stay_internet_site
   * @mbg.generated
   */
  public String getStayInternetSite() {
    return stayInternetSite;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.stay_internet_site
   *
   * @param stayInternetSite the value for special_person.stay_internet_site
   * @mbg.generated
   */
  public void setStayInternetSite(String stayInternetSite) {
    this.stayInternetSite = stayInternetSite == null ? null : stayInternetSite.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.tj_time_reason
   *
   * @return the value of special_person.tj_time_reason
   * @mbg.generated
   */
  public String getTjTimeReason() {
    return tjTimeReason;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.tj_time_reason
   *
   * @param tjTimeReason the value for special_person.tj_time_reason
   * @mbg.generated
   */
  public void setTjTimeReason(String tjTimeReason) {
    this.tjTimeReason = tjTimeReason == null ? null : tjTimeReason.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.vehicle
   *
   * @return the value of special_person.vehicle
   * @mbg.generated
   */
  public String getVehicle() {
    return vehicle;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.vehicle
   *
   * @param vehicle the value for special_person.vehicle
   * @mbg.generated
   */
  public void setVehicle(String vehicle) {
    this.vehicle = vehicle == null ? null : vehicle.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.tj_stay_site
   *
   * @return the value of special_person.tj_stay_site
   * @mbg.generated
   */
  public String getTjStaySite() {
    return tjStaySite;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.tj_stay_site
   *
   * @param tjStaySite the value for special_person.tj_stay_site
   * @mbg.generated
   */
  public void setTjStaySite(String tjStaySite) {
    this.tjStaySite = tjStaySite == null ? null : tjStaySite.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.tj_contact
   *
   * @return the value of special_person.tj_contact
   * @mbg.generated
   */
  public String getTjContact() {
    return tjContact;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.tj_contact
   *
   * @param tjContact the value for special_person.tj_contact
   * @mbg.generated
   */
  public void setTjContact(String tjContact) {
    this.tjContact = tjContact == null ? null : tjContact.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.belongings
   *
   * @return the value of special_person.belongings
   * @mbg.generated
   */
  public String getBelongings() {
    return belongings;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.belongings
   *
   * @param belongings the value for special_person.belongings
   * @mbg.generated
   */
  public void setBelongings(String belongings) {
    this.belongings = belongings == null ? null : belongings.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.virtual_identity
   *
   * @return the value of special_person.virtual_identity
   * @mbg.generated
   */
  public String getVirtualIdentity() {
    return virtualIdentity;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.virtual_identity
   *
   * @param virtualIdentity the value for special_person.virtual_identity
   * @mbg.generated
   */
  public void setVirtualIdentity(String virtualIdentity) {
    this.virtualIdentity = virtualIdentity == null ? null : virtualIdentity.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.peer_staff
   *
   * @return the value of special_person.peer_staff
   * @mbg.generated
   */
  public String getPeerStaff() {
    return peerStaff;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.peer_staff
   *
   * @param peerStaff the value for special_person.peer_staff
   * @mbg.generated
   */
  public void setPeerStaff(String peerStaff) {
    this.peerStaff = peerStaff == null ? null : peerStaff.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.stay_staff
   *
   * @return the value of special_person.stay_staff
   * @mbg.generated
   */
  public String getStayStaff() {
    return stayStaff;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.stay_staff
   *
   * @param stayStaff the value for special_person.stay_staff
   * @mbg.generated
   */
  public void setStayStaff(String stayStaff) {
    this.stayStaff = stayStaff == null ? null : stayStaff.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.car_num
   *
   * @return the value of special_person.car_num
   * @mbg.generated
   */
  public String getCarNum() {
    return carNum;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.car_num
   *
   * @param carNum the value for special_person.car_num
   * @mbg.generated
   */
  public void setCarNum(String carNum) {
    this.carNum = carNum == null ? null : carNum.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.terrorist_char
   *
   * @return the value of special_person.terrorist_char
   * @mbg.generated
   */
  public String getTerroristChar() {
    return terroristChar;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.terrorist_char
   *
   * @param terroristChar the value for special_person.terrorist_char
   * @mbg.generated
   */
  public void setTerroristChar(String terroristChar) {
    this.terroristChar = terroristChar == null ? null : terroristChar.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.control_type
   *
   * @return the value of special_person.control_type
   * @mbg.generated
   */
  public String getControlType() {
    return controlType;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.control_type
   *
   * @param controlType the value for special_person.control_type
   * @mbg.generated
   */
  public void setControlType(String controlType) {
    this.controlType = controlType == null ? null : controlType.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.check_site
   *
   * @return the value of special_person.check_site
   * @mbg.generated
   */
  public String getCheckSite() {
    return checkSite;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.check_site
   *
   * @param checkSite the value for special_person.check_site
   * @mbg.generated
   */
  public void setCheckSite(String checkSite) {
    this.checkSite = checkSite == null ? null : checkSite.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.check_police
   *
   * @return the value of special_person.check_police
   * @mbg.generated
   */
  public String getCheckPolice() {
    return checkPolice;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.check_police
   *
   * @param checkPolice the value for special_person.check_police
   * @mbg.generated
   */
  public void setCheckPolice(String checkPolice) {
    this.checkPolice = checkPolice == null ? null : checkPolice.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.ext1
   *
   * @return the value of special_person.ext1
   * @mbg.generated
   */
  public String getExt1() {
    return ext1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.ext1
   *
   * @param ext1 the value for special_person.ext1
   * @mbg.generated
   */
  public void setExt1(String ext1) {
    this.ext1 = ext1 == null ? null : ext1.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.ext2
   *
   * @return the value of special_person.ext2
   * @mbg.generated
   */
  public String getExt2() {
    return ext2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.ext2
   *
   * @param ext2 the value for special_person.ext2
   * @mbg.generated
   */
  public void setExt2(String ext2) {
    this.ext2 = ext2 == null ? null : ext2.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.ext3
   *
   * @return the value of special_person.ext3
   * @mbg.generated
   */
  public String getExt3() {
    return ext3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.ext3
   *
   * @param ext3 the value for special_person.ext3
   * @mbg.generated
   */
  public void setExt3(String ext3) {
    this.ext3 = ext3 == null ? null : ext3.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column special_person.delete_flag
   *
   * @return the value of special_person.delete_flag
   * @mbg.generated
   */
  public Boolean getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column special_person.delete_flag
   *
   * @param deleteFlag the value for special_person.delete_flag
   * @mbg.generated
   */
  public void setDeleteFlag(Boolean deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}