package cn.qsky.policesys.core.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SpecialPersonModelExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public SpecialPersonModelExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNull() {
      addCriterion("created_time is null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIsNotNull() {
      addCriterion("created_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeEqualTo(Date value) {
      addCriterion("created_time =", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotEqualTo(Date value) {
      addCriterion("created_time <>", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThan(Date value) {
      addCriterion("created_time >", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("created_time >=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThan(Date value) {
      addCriterion("created_time <", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
      addCriterion("created_time <=", value, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeIn(List<Date> values) {
      addCriterion("created_time in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotIn(List<Date> values) {
      addCriterion("created_time not in", values, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeBetween(Date value1, Date value2) {
      addCriterion("created_time between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
      addCriterion("created_time not between", value1, value2, "createdTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNull() {
      addCriterion("modified_time is null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIsNotNull() {
      addCriterion("modified_time is not null");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeEqualTo(Date value) {
      addCriterion("modified_time =", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotEqualTo(Date value) {
      addCriterion("modified_time <>", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThan(Date value) {
      addCriterion("modified_time >", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("modified_time >=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThan(Date value) {
      addCriterion("modified_time <", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
      addCriterion("modified_time <=", value, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeIn(List<Date> values) {
      addCriterion("modified_time in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotIn(List<Date> values) {
      addCriterion("modified_time not in", values, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeBetween(Date value1, Date value2) {
      addCriterion("modified_time between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
      addCriterion("modified_time not between", value1, value2, "modifiedTime");
      return (Criteria) this;
    }

    public Criteria andNameIsNull() {
      addCriterion("name is null");
      return (Criteria) this;
    }

    public Criteria andNameIsNotNull() {
      addCriterion("name is not null");
      return (Criteria) this;
    }

    public Criteria andNameEqualTo(String value) {
      addCriterion("name =", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotEqualTo(String value) {
      addCriterion("name <>", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThan(String value) {
      addCriterion("name >", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThanOrEqualTo(String value) {
      addCriterion("name >=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThan(String value) {
      addCriterion("name <", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThanOrEqualTo(String value) {
      addCriterion("name <=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLike(String value) {
      addCriterion("name like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotLike(String value) {
      addCriterion("name not like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameIn(List<String> values) {
      addCriterion("name in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotIn(List<String> values) {
      addCriterion("name not in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameBetween(String value1, String value2) {
      addCriterion("name between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotBetween(String value1, String value2) {
      addCriterion("name not between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andIdCardIsNull() {
      addCriterion("id_card is null");
      return (Criteria) this;
    }

    public Criteria andIdCardIsNotNull() {
      addCriterion("id_card is not null");
      return (Criteria) this;
    }

    public Criteria andIdCardEqualTo(String value) {
      addCriterion("id_card =", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotEqualTo(String value) {
      addCriterion("id_card <>", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardGreaterThan(String value) {
      addCriterion("id_card >", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardGreaterThanOrEqualTo(String value) {
      addCriterion("id_card >=", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardLessThan(String value) {
      addCriterion("id_card <", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardLessThanOrEqualTo(String value) {
      addCriterion("id_card <=", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardLike(String value) {
      addCriterion("id_card like", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotLike(String value) {
      addCriterion("id_card not like", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardIn(List<String> values) {
      addCriterion("id_card in", values, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotIn(List<String> values) {
      addCriterion("id_card not in", values, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardBetween(String value1, String value2) {
      addCriterion("id_card between", value1, value2, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotBetween(String value1, String value2) {
      addCriterion("id_card not between", value1, value2, "idCard");
      return (Criteria) this;
    }

    public Criteria andPhoneIsNull() {
      addCriterion("phone is null");
      return (Criteria) this;
    }

    public Criteria andPhoneIsNotNull() {
      addCriterion("phone is not null");
      return (Criteria) this;
    }

    public Criteria andPhoneEqualTo(String value) {
      addCriterion("phone =", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneNotEqualTo(String value) {
      addCriterion("phone <>", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneGreaterThan(String value) {
      addCriterion("phone >", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneGreaterThanOrEqualTo(String value) {
      addCriterion("phone >=", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneLessThan(String value) {
      addCriterion("phone <", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneLessThanOrEqualTo(String value) {
      addCriterion("phone <=", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneLike(String value) {
      addCriterion("phone like", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneNotLike(String value) {
      addCriterion("phone not like", value, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneIn(List<String> values) {
      addCriterion("phone in", values, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneNotIn(List<String> values) {
      addCriterion("phone not in", values, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneBetween(String value1, String value2) {
      addCriterion("phone between", value1, value2, "phone");
      return (Criteria) this;
    }

    public Criteria andPhoneNotBetween(String value1, String value2) {
      addCriterion("phone not between", value1, value2, "phone");
      return (Criteria) this;
    }

    public Criteria andJurisdictionIsNull() {
      addCriterion("jurisdiction is null");
      return (Criteria) this;
    }

    public Criteria andJurisdictionIsNotNull() {
      addCriterion("jurisdiction is not null");
      return (Criteria) this;
    }

    public Criteria andJurisdictionEqualTo(String value) {
      addCriterion("jurisdiction =", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionNotEqualTo(String value) {
      addCriterion("jurisdiction <>", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionGreaterThan(String value) {
      addCriterion("jurisdiction >", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionGreaterThanOrEqualTo(String value) {
      addCriterion("jurisdiction >=", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionLessThan(String value) {
      addCriterion("jurisdiction <", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionLessThanOrEqualTo(String value) {
      addCriterion("jurisdiction <=", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionLike(String value) {
      addCriterion("jurisdiction like", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionNotLike(String value) {
      addCriterion("jurisdiction not like", value, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionIn(List<String> values) {
      addCriterion("jurisdiction in", values, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionNotIn(List<String> values) {
      addCriterion("jurisdiction not in", values, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionBetween(String value1, String value2) {
      addCriterion("jurisdiction between", value1, value2, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andJurisdictionNotBetween(String value1, String value2) {
      addCriterion("jurisdiction not between", value1, value2, "jurisdiction");
      return (Criteria) this;
    }

    public Criteria andResourceNameIsNull() {
      addCriterion("resource_name is null");
      return (Criteria) this;
    }

    public Criteria andResourceNameIsNotNull() {
      addCriterion("resource_name is not null");
      return (Criteria) this;
    }

    public Criteria andResourceNameEqualTo(String value) {
      addCriterion("resource_name =", value, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameNotEqualTo(String value) {
      addCriterion("resource_name <>", value, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameGreaterThan(String value) {
      addCriterion("resource_name >", value, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameGreaterThanOrEqualTo(String value) {
      addCriterion("resource_name >=", value, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameLessThan(String value) {
      addCriterion("resource_name <", value, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameLessThanOrEqualTo(String value) {
      addCriterion("resource_name <=", value, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameLike(String value) {
      addCriterion("resource_name like", value, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameNotLike(String value) {
      addCriterion("resource_name not like", value, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameIn(List<String> values) {
      addCriterion("resource_name in", values, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameNotIn(List<String> values) {
      addCriterion("resource_name not in", values, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameBetween(String value1, String value2) {
      addCriterion("resource_name between", value1, value2, "resourceName");
      return (Criteria) this;
    }

    public Criteria andResourceNameNotBetween(String value1, String value2) {
      addCriterion("resource_name not between", value1, value2, "resourceName");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceIsNull() {
      addCriterion("activity_place is null");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceIsNotNull() {
      addCriterion("activity_place is not null");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceEqualTo(String value) {
      addCriterion("activity_place =", value, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceNotEqualTo(String value) {
      addCriterion("activity_place <>", value, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceGreaterThan(String value) {
      addCriterion("activity_place >", value, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceGreaterThanOrEqualTo(String value) {
      addCriterion("activity_place >=", value, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceLessThan(String value) {
      addCriterion("activity_place <", value, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceLessThanOrEqualTo(String value) {
      addCriterion("activity_place <=", value, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceLike(String value) {
      addCriterion("activity_place like", value, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceNotLike(String value) {
      addCriterion("activity_place not like", value, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceIn(List<String> values) {
      addCriterion("activity_place in", values, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceNotIn(List<String> values) {
      addCriterion("activity_place not in", values, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceBetween(String value1, String value2) {
      addCriterion("activity_place between", value1, value2, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceNotBetween(String value1, String value2) {
      addCriterion("activity_place not between", value1, value2, "activityPlace");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailIsNull() {
      addCriterion("activity_place_detail is null");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailIsNotNull() {
      addCriterion("activity_place_detail is not null");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailEqualTo(String value) {
      addCriterion("activity_place_detail =", value, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailNotEqualTo(String value) {
      addCriterion("activity_place_detail <>", value, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailGreaterThan(String value) {
      addCriterion("activity_place_detail >", value, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailGreaterThanOrEqualTo(String value) {
      addCriterion("activity_place_detail >=", value, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailLessThan(String value) {
      addCriterion("activity_place_detail <", value, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailLessThanOrEqualTo(String value) {
      addCriterion("activity_place_detail <=", value, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailLike(String value) {
      addCriterion("activity_place_detail like", value, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailNotLike(String value) {
      addCriterion("activity_place_detail not like", value, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailIn(List<String> values) {
      addCriterion("activity_place_detail in", values, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailNotIn(List<String> values) {
      addCriterion("activity_place_detail not in", values, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailBetween(String value1, String value2) {
      addCriterion("activity_place_detail between", value1, value2, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityPlaceDetailNotBetween(String value1, String value2) {
      addCriterion("activity_place_detail not between", value1, value2, "activityPlaceDetail");
      return (Criteria) this;
    }

    public Criteria andActivityTimeIsNull() {
      addCriterion("activity_time is null");
      return (Criteria) this;
    }

    public Criteria andActivityTimeIsNotNull() {
      addCriterion("activity_time is not null");
      return (Criteria) this;
    }

    public Criteria andActivityTimeEqualTo(Date value) {
      addCriterion("activity_time =", value, "activityTime");
      return (Criteria) this;
    }

    public Criteria andActivityTimeNotEqualTo(Date value) {
      addCriterion("activity_time <>", value, "activityTime");
      return (Criteria) this;
    }

    public Criteria andActivityTimeGreaterThan(Date value) {
      addCriterion("activity_time >", value, "activityTime");
      return (Criteria) this;
    }

    public Criteria andActivityTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("activity_time >=", value, "activityTime");
      return (Criteria) this;
    }

    public Criteria andActivityTimeLessThan(Date value) {
      addCriterion("activity_time <", value, "activityTime");
      return (Criteria) this;
    }

    public Criteria andActivityTimeLessThanOrEqualTo(Date value) {
      addCriterion("activity_time <=", value, "activityTime");
      return (Criteria) this;
    }

    public Criteria andActivityTimeIn(List<Date> values) {
      addCriterion("activity_time in", values, "activityTime");
      return (Criteria) this;
    }

    public Criteria andActivityTimeNotIn(List<Date> values) {
      addCriterion("activity_time not in", values, "activityTime");
      return (Criteria) this;
    }

    public Criteria andActivityTimeBetween(Date value1, Date value2) {
      addCriterion("activity_time between", value1, value2, "activityTime");
      return (Criteria) this;
    }

    public Criteria andActivityTimeNotBetween(Date value1, Date value2) {
      addCriterion("activity_time not between", value1, value2, "activityTime");
      return (Criteria) this;
    }

    public Criteria andPushTimeIsNull() {
      addCriterion("push_time is null");
      return (Criteria) this;
    }

    public Criteria andPushTimeIsNotNull() {
      addCriterion("push_time is not null");
      return (Criteria) this;
    }

    public Criteria andPushTimeEqualTo(Date value) {
      addCriterion("push_time =", value, "pushTime");
      return (Criteria) this;
    }

    public Criteria andPushTimeNotEqualTo(Date value) {
      addCriterion("push_time <>", value, "pushTime");
      return (Criteria) this;
    }

    public Criteria andPushTimeGreaterThan(Date value) {
      addCriterion("push_time >", value, "pushTime");
      return (Criteria) this;
    }

    public Criteria andPushTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("push_time >=", value, "pushTime");
      return (Criteria) this;
    }

    public Criteria andPushTimeLessThan(Date value) {
      addCriterion("push_time <", value, "pushTime");
      return (Criteria) this;
    }

    public Criteria andPushTimeLessThanOrEqualTo(Date value) {
      addCriterion("push_time <=", value, "pushTime");
      return (Criteria) this;
    }

    public Criteria andPushTimeIn(List<Date> values) {
      addCriterion("push_time in", values, "pushTime");
      return (Criteria) this;
    }

    public Criteria andPushTimeNotIn(List<Date> values) {
      addCriterion("push_time not in", values, "pushTime");
      return (Criteria) this;
    }

    public Criteria andPushTimeBetween(Date value1, Date value2) {
      addCriterion("push_time between", value1, value2, "pushTime");
      return (Criteria) this;
    }

    public Criteria andPushTimeNotBetween(Date value1, Date value2) {
      addCriterion("push_time not between", value1, value2, "pushTime");
      return (Criteria) this;
    }

    public Criteria andDomicileIsNull() {
      addCriterion("domicile is null");
      return (Criteria) this;
    }

    public Criteria andDomicileIsNotNull() {
      addCriterion("domicile is not null");
      return (Criteria) this;
    }

    public Criteria andDomicileEqualTo(String value) {
      addCriterion("domicile =", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileNotEqualTo(String value) {
      addCriterion("domicile <>", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileGreaterThan(String value) {
      addCriterion("domicile >", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileGreaterThanOrEqualTo(String value) {
      addCriterion("domicile >=", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileLessThan(String value) {
      addCriterion("domicile <", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileLessThanOrEqualTo(String value) {
      addCriterion("domicile <=", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileLike(String value) {
      addCriterion("domicile like", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileNotLike(String value) {
      addCriterion("domicile not like", value, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileIn(List<String> values) {
      addCriterion("domicile in", values, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileNotIn(List<String> values) {
      addCriterion("domicile not in", values, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileBetween(String value1, String value2) {
      addCriterion("domicile between", value1, value2, "domicile");
      return (Criteria) this;
    }

    public Criteria andDomicileNotBetween(String value1, String value2) {
      addCriterion("domicile not between", value1, value2, "domicile");
      return (Criteria) this;
    }

    public Criteria andNationIsNull() {
      addCriterion("nation is null");
      return (Criteria) this;
    }

    public Criteria andNationIsNotNull() {
      addCriterion("nation is not null");
      return (Criteria) this;
    }

    public Criteria andNationEqualTo(String value) {
      addCriterion("nation =", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationNotEqualTo(String value) {
      addCriterion("nation <>", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationGreaterThan(String value) {
      addCriterion("nation >", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationGreaterThanOrEqualTo(String value) {
      addCriterion("nation >=", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationLessThan(String value) {
      addCriterion("nation <", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationLessThanOrEqualTo(String value) {
      addCriterion("nation <=", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationLike(String value) {
      addCriterion("nation like", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationNotLike(String value) {
      addCriterion("nation not like", value, "nation");
      return (Criteria) this;
    }

    public Criteria andNationIn(List<String> values) {
      addCriterion("nation in", values, "nation");
      return (Criteria) this;
    }

    public Criteria andNationNotIn(List<String> values) {
      addCriterion("nation not in", values, "nation");
      return (Criteria) this;
    }

    public Criteria andNationBetween(String value1, String value2) {
      addCriterion("nation between", value1, value2, "nation");
      return (Criteria) this;
    }

    public Criteria andNationNotBetween(String value1, String value2) {
      addCriterion("nation not between", value1, value2, "nation");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteIsNull() {
      addCriterion("stay_internet_site is null");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteIsNotNull() {
      addCriterion("stay_internet_site is not null");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteEqualTo(String value) {
      addCriterion("stay_internet_site =", value, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteNotEqualTo(String value) {
      addCriterion("stay_internet_site <>", value, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteGreaterThan(String value) {
      addCriterion("stay_internet_site >", value, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteGreaterThanOrEqualTo(String value) {
      addCriterion("stay_internet_site >=", value, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteLessThan(String value) {
      addCriterion("stay_internet_site <", value, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteLessThanOrEqualTo(String value) {
      addCriterion("stay_internet_site <=", value, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteLike(String value) {
      addCriterion("stay_internet_site like", value, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteNotLike(String value) {
      addCriterion("stay_internet_site not like", value, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteIn(List<String> values) {
      addCriterion("stay_internet_site in", values, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteNotIn(List<String> values) {
      addCriterion("stay_internet_site not in", values, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteBetween(String value1, String value2) {
      addCriterion("stay_internet_site between", value1, value2, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andStayInternetSiteNotBetween(String value1, String value2) {
      addCriterion("stay_internet_site not between", value1, value2, "stayInternetSite");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonIsNull() {
      addCriterion("tj_time_reason is null");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonIsNotNull() {
      addCriterion("tj_time_reason is not null");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonEqualTo(String value) {
      addCriterion("tj_time_reason =", value, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonNotEqualTo(String value) {
      addCriterion("tj_time_reason <>", value, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonGreaterThan(String value) {
      addCriterion("tj_time_reason >", value, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonGreaterThanOrEqualTo(String value) {
      addCriterion("tj_time_reason >=", value, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonLessThan(String value) {
      addCriterion("tj_time_reason <", value, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonLessThanOrEqualTo(String value) {
      addCriterion("tj_time_reason <=", value, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonLike(String value) {
      addCriterion("tj_time_reason like", value, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonNotLike(String value) {
      addCriterion("tj_time_reason not like", value, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonIn(List<String> values) {
      addCriterion("tj_time_reason in", values, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonNotIn(List<String> values) {
      addCriterion("tj_time_reason not in", values, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonBetween(String value1, String value2) {
      addCriterion("tj_time_reason between", value1, value2, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andTjTimeReasonNotBetween(String value1, String value2) {
      addCriterion("tj_time_reason not between", value1, value2, "tjTimeReason");
      return (Criteria) this;
    }

    public Criteria andVehicleIsNull() {
      addCriterion("vehicle is null");
      return (Criteria) this;
    }

    public Criteria andVehicleIsNotNull() {
      addCriterion("vehicle is not null");
      return (Criteria) this;
    }

    public Criteria andVehicleEqualTo(String value) {
      addCriterion("vehicle =", value, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleNotEqualTo(String value) {
      addCriterion("vehicle <>", value, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleGreaterThan(String value) {
      addCriterion("vehicle >", value, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleGreaterThanOrEqualTo(String value) {
      addCriterion("vehicle >=", value, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleLessThan(String value) {
      addCriterion("vehicle <", value, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleLessThanOrEqualTo(String value) {
      addCriterion("vehicle <=", value, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleLike(String value) {
      addCriterion("vehicle like", value, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleNotLike(String value) {
      addCriterion("vehicle not like", value, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleIn(List<String> values) {
      addCriterion("vehicle in", values, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleNotIn(List<String> values) {
      addCriterion("vehicle not in", values, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleBetween(String value1, String value2) {
      addCriterion("vehicle between", value1, value2, "vehicle");
      return (Criteria) this;
    }

    public Criteria andVehicleNotBetween(String value1, String value2) {
      addCriterion("vehicle not between", value1, value2, "vehicle");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteIsNull() {
      addCriterion("tj_stay_site is null");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteIsNotNull() {
      addCriterion("tj_stay_site is not null");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteEqualTo(String value) {
      addCriterion("tj_stay_site =", value, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteNotEqualTo(String value) {
      addCriterion("tj_stay_site <>", value, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteGreaterThan(String value) {
      addCriterion("tj_stay_site >", value, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteGreaterThanOrEqualTo(String value) {
      addCriterion("tj_stay_site >=", value, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteLessThan(String value) {
      addCriterion("tj_stay_site <", value, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteLessThanOrEqualTo(String value) {
      addCriterion("tj_stay_site <=", value, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteLike(String value) {
      addCriterion("tj_stay_site like", value, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteNotLike(String value) {
      addCriterion("tj_stay_site not like", value, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteIn(List<String> values) {
      addCriterion("tj_stay_site in", values, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteNotIn(List<String> values) {
      addCriterion("tj_stay_site not in", values, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteBetween(String value1, String value2) {
      addCriterion("tj_stay_site between", value1, value2, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjStaySiteNotBetween(String value1, String value2) {
      addCriterion("tj_stay_site not between", value1, value2, "tjStaySite");
      return (Criteria) this;
    }

    public Criteria andTjContactIsNull() {
      addCriterion("tj_contact is null");
      return (Criteria) this;
    }

    public Criteria andTjContactIsNotNull() {
      addCriterion("tj_contact is not null");
      return (Criteria) this;
    }

    public Criteria andTjContactEqualTo(String value) {
      addCriterion("tj_contact =", value, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactNotEqualTo(String value) {
      addCriterion("tj_contact <>", value, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactGreaterThan(String value) {
      addCriterion("tj_contact >", value, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactGreaterThanOrEqualTo(String value) {
      addCriterion("tj_contact >=", value, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactLessThan(String value) {
      addCriterion("tj_contact <", value, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactLessThanOrEqualTo(String value) {
      addCriterion("tj_contact <=", value, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactLike(String value) {
      addCriterion("tj_contact like", value, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactNotLike(String value) {
      addCriterion("tj_contact not like", value, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactIn(List<String> values) {
      addCriterion("tj_contact in", values, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactNotIn(List<String> values) {
      addCriterion("tj_contact not in", values, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactBetween(String value1, String value2) {
      addCriterion("tj_contact between", value1, value2, "tjContact");
      return (Criteria) this;
    }

    public Criteria andTjContactNotBetween(String value1, String value2) {
      addCriterion("tj_contact not between", value1, value2, "tjContact");
      return (Criteria) this;
    }

    public Criteria andBelongingsIsNull() {
      addCriterion("belongings is null");
      return (Criteria) this;
    }

    public Criteria andBelongingsIsNotNull() {
      addCriterion("belongings is not null");
      return (Criteria) this;
    }

    public Criteria andBelongingsEqualTo(String value) {
      addCriterion("belongings =", value, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsNotEqualTo(String value) {
      addCriterion("belongings <>", value, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsGreaterThan(String value) {
      addCriterion("belongings >", value, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsGreaterThanOrEqualTo(String value) {
      addCriterion("belongings >=", value, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsLessThan(String value) {
      addCriterion("belongings <", value, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsLessThanOrEqualTo(String value) {
      addCriterion("belongings <=", value, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsLike(String value) {
      addCriterion("belongings like", value, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsNotLike(String value) {
      addCriterion("belongings not like", value, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsIn(List<String> values) {
      addCriterion("belongings in", values, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsNotIn(List<String> values) {
      addCriterion("belongings not in", values, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsBetween(String value1, String value2) {
      addCriterion("belongings between", value1, value2, "belongings");
      return (Criteria) this;
    }

    public Criteria andBelongingsNotBetween(String value1, String value2) {
      addCriterion("belongings not between", value1, value2, "belongings");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityIsNull() {
      addCriterion("virtual_identity is null");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityIsNotNull() {
      addCriterion("virtual_identity is not null");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityEqualTo(String value) {
      addCriterion("virtual_identity =", value, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityNotEqualTo(String value) {
      addCriterion("virtual_identity <>", value, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityGreaterThan(String value) {
      addCriterion("virtual_identity >", value, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityGreaterThanOrEqualTo(String value) {
      addCriterion("virtual_identity >=", value, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityLessThan(String value) {
      addCriterion("virtual_identity <", value, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityLessThanOrEqualTo(String value) {
      addCriterion("virtual_identity <=", value, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityLike(String value) {
      addCriterion("virtual_identity like", value, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityNotLike(String value) {
      addCriterion("virtual_identity not like", value, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityIn(List<String> values) {
      addCriterion("virtual_identity in", values, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityNotIn(List<String> values) {
      addCriterion("virtual_identity not in", values, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityBetween(String value1, String value2) {
      addCriterion("virtual_identity between", value1, value2, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andVirtualIdentityNotBetween(String value1, String value2) {
      addCriterion("virtual_identity not between", value1, value2, "virtualIdentity");
      return (Criteria) this;
    }

    public Criteria andPeerStaffIsNull() {
      addCriterion("peer_staff is null");
      return (Criteria) this;
    }

    public Criteria andPeerStaffIsNotNull() {
      addCriterion("peer_staff is not null");
      return (Criteria) this;
    }

    public Criteria andPeerStaffEqualTo(String value) {
      addCriterion("peer_staff =", value, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffNotEqualTo(String value) {
      addCriterion("peer_staff <>", value, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffGreaterThan(String value) {
      addCriterion("peer_staff >", value, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffGreaterThanOrEqualTo(String value) {
      addCriterion("peer_staff >=", value, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffLessThan(String value) {
      addCriterion("peer_staff <", value, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffLessThanOrEqualTo(String value) {
      addCriterion("peer_staff <=", value, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffLike(String value) {
      addCriterion("peer_staff like", value, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffNotLike(String value) {
      addCriterion("peer_staff not like", value, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffIn(List<String> values) {
      addCriterion("peer_staff in", values, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffNotIn(List<String> values) {
      addCriterion("peer_staff not in", values, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffBetween(String value1, String value2) {
      addCriterion("peer_staff between", value1, value2, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andPeerStaffNotBetween(String value1, String value2) {
      addCriterion("peer_staff not between", value1, value2, "peerStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffIsNull() {
      addCriterion("stay_staff is null");
      return (Criteria) this;
    }

    public Criteria andStayStaffIsNotNull() {
      addCriterion("stay_staff is not null");
      return (Criteria) this;
    }

    public Criteria andStayStaffEqualTo(String value) {
      addCriterion("stay_staff =", value, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffNotEqualTo(String value) {
      addCriterion("stay_staff <>", value, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffGreaterThan(String value) {
      addCriterion("stay_staff >", value, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffGreaterThanOrEqualTo(String value) {
      addCriterion("stay_staff >=", value, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffLessThan(String value) {
      addCriterion("stay_staff <", value, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffLessThanOrEqualTo(String value) {
      addCriterion("stay_staff <=", value, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffLike(String value) {
      addCriterion("stay_staff like", value, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffNotLike(String value) {
      addCriterion("stay_staff not like", value, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffIn(List<String> values) {
      addCriterion("stay_staff in", values, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffNotIn(List<String> values) {
      addCriterion("stay_staff not in", values, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffBetween(String value1, String value2) {
      addCriterion("stay_staff between", value1, value2, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andStayStaffNotBetween(String value1, String value2) {
      addCriterion("stay_staff not between", value1, value2, "stayStaff");
      return (Criteria) this;
    }

    public Criteria andCarNumIsNull() {
      addCriterion("car_num is null");
      return (Criteria) this;
    }

    public Criteria andCarNumIsNotNull() {
      addCriterion("car_num is not null");
      return (Criteria) this;
    }

    public Criteria andCarNumEqualTo(String value) {
      addCriterion("car_num =", value, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumNotEqualTo(String value) {
      addCriterion("car_num <>", value, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumGreaterThan(String value) {
      addCriterion("car_num >", value, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumGreaterThanOrEqualTo(String value) {
      addCriterion("car_num >=", value, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumLessThan(String value) {
      addCriterion("car_num <", value, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumLessThanOrEqualTo(String value) {
      addCriterion("car_num <=", value, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumLike(String value) {
      addCriterion("car_num like", value, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumNotLike(String value) {
      addCriterion("car_num not like", value, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumIn(List<String> values) {
      addCriterion("car_num in", values, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumNotIn(List<String> values) {
      addCriterion("car_num not in", values, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumBetween(String value1, String value2) {
      addCriterion("car_num between", value1, value2, "carNum");
      return (Criteria) this;
    }

    public Criteria andCarNumNotBetween(String value1, String value2) {
      addCriterion("car_num not between", value1, value2, "carNum");
      return (Criteria) this;
    }

    public Criteria andTerroristCharIsNull() {
      addCriterion("terrorist_char is null");
      return (Criteria) this;
    }

    public Criteria andTerroristCharIsNotNull() {
      addCriterion("terrorist_char is not null");
      return (Criteria) this;
    }

    public Criteria andTerroristCharEqualTo(String value) {
      addCriterion("terrorist_char =", value, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharNotEqualTo(String value) {
      addCriterion("terrorist_char <>", value, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharGreaterThan(String value) {
      addCriterion("terrorist_char >", value, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharGreaterThanOrEqualTo(String value) {
      addCriterion("terrorist_char >=", value, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharLessThan(String value) {
      addCriterion("terrorist_char <", value, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharLessThanOrEqualTo(String value) {
      addCriterion("terrorist_char <=", value, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharLike(String value) {
      addCriterion("terrorist_char like", value, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharNotLike(String value) {
      addCriterion("terrorist_char not like", value, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharIn(List<String> values) {
      addCriterion("terrorist_char in", values, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharNotIn(List<String> values) {
      addCriterion("terrorist_char not in", values, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharBetween(String value1, String value2) {
      addCriterion("terrorist_char between", value1, value2, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andTerroristCharNotBetween(String value1, String value2) {
      addCriterion("terrorist_char not between", value1, value2, "terroristChar");
      return (Criteria) this;
    }

    public Criteria andControlTypeIsNull() {
      addCriterion("control_type is null");
      return (Criteria) this;
    }

    public Criteria andControlTypeIsNotNull() {
      addCriterion("control_type is not null");
      return (Criteria) this;
    }

    public Criteria andControlTypeEqualTo(String value) {
      addCriterion("control_type =", value, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeNotEqualTo(String value) {
      addCriterion("control_type <>", value, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeGreaterThan(String value) {
      addCriterion("control_type >", value, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeGreaterThanOrEqualTo(String value) {
      addCriterion("control_type >=", value, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeLessThan(String value) {
      addCriterion("control_type <", value, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeLessThanOrEqualTo(String value) {
      addCriterion("control_type <=", value, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeLike(String value) {
      addCriterion("control_type like", value, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeNotLike(String value) {
      addCriterion("control_type not like", value, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeIn(List<String> values) {
      addCriterion("control_type in", values, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeNotIn(List<String> values) {
      addCriterion("control_type not in", values, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeBetween(String value1, String value2) {
      addCriterion("control_type between", value1, value2, "controlType");
      return (Criteria) this;
    }

    public Criteria andControlTypeNotBetween(String value1, String value2) {
      addCriterion("control_type not between", value1, value2, "controlType");
      return (Criteria) this;
    }

    public Criteria andCheckSiteIsNull() {
      addCriterion("check_site is null");
      return (Criteria) this;
    }

    public Criteria andCheckSiteIsNotNull() {
      addCriterion("check_site is not null");
      return (Criteria) this;
    }

    public Criteria andCheckSiteEqualTo(String value) {
      addCriterion("check_site =", value, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteNotEqualTo(String value) {
      addCriterion("check_site <>", value, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteGreaterThan(String value) {
      addCriterion("check_site >", value, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteGreaterThanOrEqualTo(String value) {
      addCriterion("check_site >=", value, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteLessThan(String value) {
      addCriterion("check_site <", value, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteLessThanOrEqualTo(String value) {
      addCriterion("check_site <=", value, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteLike(String value) {
      addCriterion("check_site like", value, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteNotLike(String value) {
      addCriterion("check_site not like", value, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteIn(List<String> values) {
      addCriterion("check_site in", values, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteNotIn(List<String> values) {
      addCriterion("check_site not in", values, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteBetween(String value1, String value2) {
      addCriterion("check_site between", value1, value2, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckSiteNotBetween(String value1, String value2) {
      addCriterion("check_site not between", value1, value2, "checkSite");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceIsNull() {
      addCriterion("check_police is null");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceIsNotNull() {
      addCriterion("check_police is not null");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceEqualTo(String value) {
      addCriterion("check_police =", value, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceNotEqualTo(String value) {
      addCriterion("check_police <>", value, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceGreaterThan(String value) {
      addCriterion("check_police >", value, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceGreaterThanOrEqualTo(String value) {
      addCriterion("check_police >=", value, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceLessThan(String value) {
      addCriterion("check_police <", value, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceLessThanOrEqualTo(String value) {
      addCriterion("check_police <=", value, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceLike(String value) {
      addCriterion("check_police like", value, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceNotLike(String value) {
      addCriterion("check_police not like", value, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceIn(List<String> values) {
      addCriterion("check_police in", values, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceNotIn(List<String> values) {
      addCriterion("check_police not in", values, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceBetween(String value1, String value2) {
      addCriterion("check_police between", value1, value2, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andCheckPoliceNotBetween(String value1, String value2) {
      addCriterion("check_police not between", value1, value2, "checkPolice");
      return (Criteria) this;
    }

    public Criteria andExt1IsNull() {
      addCriterion("ext1 is null");
      return (Criteria) this;
    }

    public Criteria andExt1IsNotNull() {
      addCriterion("ext1 is not null");
      return (Criteria) this;
    }

    public Criteria andExt1EqualTo(String value) {
      addCriterion("ext1 =", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotEqualTo(String value) {
      addCriterion("ext1 <>", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThan(String value) {
      addCriterion("ext1 >", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1GreaterThanOrEqualTo(String value) {
      addCriterion("ext1 >=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThan(String value) {
      addCriterion("ext1 <", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1LessThanOrEqualTo(String value) {
      addCriterion("ext1 <=", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Like(String value) {
      addCriterion("ext1 like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotLike(String value) {
      addCriterion("ext1 not like", value, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1In(List<String> values) {
      addCriterion("ext1 in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotIn(List<String> values) {
      addCriterion("ext1 not in", values, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1Between(String value1, String value2) {
      addCriterion("ext1 between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt1NotBetween(String value1, String value2) {
      addCriterion("ext1 not between", value1, value2, "ext1");
      return (Criteria) this;
    }

    public Criteria andExt2IsNull() {
      addCriterion("ext2 is null");
      return (Criteria) this;
    }

    public Criteria andExt2IsNotNull() {
      addCriterion("ext2 is not null");
      return (Criteria) this;
    }

    public Criteria andExt2EqualTo(String value) {
      addCriterion("ext2 =", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotEqualTo(String value) {
      addCriterion("ext2 <>", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2GreaterThan(String value) {
      addCriterion("ext2 >", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2GreaterThanOrEqualTo(String value) {
      addCriterion("ext2 >=", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2LessThan(String value) {
      addCriterion("ext2 <", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2LessThanOrEqualTo(String value) {
      addCriterion("ext2 <=", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2Like(String value) {
      addCriterion("ext2 like", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotLike(String value) {
      addCriterion("ext2 not like", value, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2In(List<String> values) {
      addCriterion("ext2 in", values, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotIn(List<String> values) {
      addCriterion("ext2 not in", values, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2Between(String value1, String value2) {
      addCriterion("ext2 between", value1, value2, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt2NotBetween(String value1, String value2) {
      addCriterion("ext2 not between", value1, value2, "ext2");
      return (Criteria) this;
    }

    public Criteria andExt3IsNull() {
      addCriterion("ext3 is null");
      return (Criteria) this;
    }

    public Criteria andExt3IsNotNull() {
      addCriterion("ext3 is not null");
      return (Criteria) this;
    }

    public Criteria andExt3EqualTo(String value) {
      addCriterion("ext3 =", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotEqualTo(String value) {
      addCriterion("ext3 <>", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3GreaterThan(String value) {
      addCriterion("ext3 >", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3GreaterThanOrEqualTo(String value) {
      addCriterion("ext3 >=", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3LessThan(String value) {
      addCriterion("ext3 <", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3LessThanOrEqualTo(String value) {
      addCriterion("ext3 <=", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3Like(String value) {
      addCriterion("ext3 like", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotLike(String value) {
      addCriterion("ext3 not like", value, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3In(List<String> values) {
      addCriterion("ext3 in", values, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotIn(List<String> values) {
      addCriterion("ext3 not in", values, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3Between(String value1, String value2) {
      addCriterion("ext3 between", value1, value2, "ext3");
      return (Criteria) this;
    }

    public Criteria andExt3NotBetween(String value1, String value2) {
      addCriterion("ext3 not between", value1, value2, "ext3");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNull() {
      addCriterion("delete_flag is null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIsNotNull() {
      addCriterion("delete_flag is not null");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagEqualTo(Boolean value) {
      addCriterion("delete_flag =", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotEqualTo(Boolean value) {
      addCriterion("delete_flag <>", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThan(Boolean value) {
      addCriterion("delete_flag >", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag >=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThan(Boolean value) {
      addCriterion("delete_flag <", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
      addCriterion("delete_flag <=", value, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagIn(List<Boolean> values) {
      addCriterion("delete_flag in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotIn(List<Boolean> values) {
      addCriterion("delete_flag not in", values, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }

    public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
      addCriterion("delete_flag not between", value1, value2, "deleteFlag");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * special_person
   *
   * @mbg.generated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * special_person
   *
   * @mbg.generated
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}